// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.4
// source: detailextractor.proto

package smartfindpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtractRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base64 data URI (data:image/jpeg;base64,...) or raw base64 bytes.
	ImageBase64   string `protobuf:"bytes,1,opt,name=image_base64,json=imageBase64,proto3" json:"image_base64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractRequest) Reset() {
	*x = ExtractRequest{}
	mi := &file_detailextractor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractRequest) ProtoMessage() {}

func (x *ExtractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_detailextractor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractRequest.ProtoReflect.Descriptor instead.
func (*ExtractRequest) Descriptor() ([]byte, []int) {
	return file_detailextractor_proto_rawDescGZIP(), []int{0}
}

func (x *ExtractRequest) GetImageBase64() string {
	if x != nil {
		return x.ImageBase64
	}
	return ""
}

type ExtractResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ItemName        string                 `protobuf:"bytes,1,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	ItemType        string                 `protobuf:"bytes,2,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	Category        string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Brand           string                 `protobuf:"bytes,4,opt,name=brand,proto3" json:"brand,omitempty"`
	Model           string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	Color           string                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	Material        string                 `protobuf:"bytes,7,opt,name=material,proto3" json:"material,omitempty"`
	ItemCondition   string                 `protobuf:"bytes,8,opt,name=item_condition,json=itemCondition,proto3" json:"item_condition,omitempty"`
	ItemDescription string                 `protobuf:"bytes,9,opt,name=item_description,json=itemDescription,proto3" json:"item_description,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExtractResponse) Reset() {
	*x = ExtractResponse{}
	mi := &file_detailextractor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractResponse) ProtoMessage() {}

func (x *ExtractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_detailextractor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractResponse.ProtoReflect.Descriptor instead.
func (*ExtractResponse) Descriptor() ([]byte, []int) {
	return file_detailextractor_proto_rawDescGZIP(), []int{1}
}

func (x *ExtractResponse) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *ExtractResponse) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *ExtractResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ExtractResponse) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *ExtractResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ExtractResponse) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ExtractResponse) GetMaterial() string {
	if x != nil {
		return x.Material
	}
	return ""
}

func (x *ExtractResponse) GetItemCondition() string {
	if x != nil {
		return x.ItemCondition
	}
	return ""
}

func (x *ExtractResponse) GetItemDescription() string {
	if x != nil {
		return x.ItemDescription
	}
	return ""
}

var File_detailextractor_proto protoreflect.FileDescriptor

const file_detailextractor_proto_rawDesc = "" +
	"\n" +
	"\x15detailextractor.proto\x12\x1csmartfind.detailextractor.v1\"3\n" +
	"\x0eExtractRequest\x12!\n" +
	"\fimage_base64\x18\x01 \x01(\tR\vimageBase64\"\x97\x02\n" +
	"\x0fExtractResponse\x12\x1b\n" +
	"\titem_name\x18\x01 \x01(\tR\bitemName\x12\x1b\n" +
	"\titem_type\x18\x02 \x01(\tR\bitemType\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x14\n" +
	"\x05brand\x18\x04 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\x12\x1a\n" +
	"\bmaterial\x18\a \x01(\tR\bmaterial\x12%\n" +
	"\x0eitem_condition\x18\b \x01(\tR\ritemCondition\x12)\n" +
	"\x10item_description\x18\t \x01(\tR\x0fitemDescription2\x80\x01\n" +
	"\x16DetailExtractorService\x12f\n" +
	"\aExtract\x12,.smartfind.detailextractor.v1.ExtractRequest\x1a-.smartfind.detailextractor.v1.ExtractResponseB\x1dZ\x1bsmartfind/proto;smartfindpbb\x06proto3"

var (
	file_detailextractor_proto_rawDescOnce sync.Once
	file_detailextractor_proto_rawDescData []byte
)

func file_detailextractor_proto_rawDescGZIP() []byte {
	file_detailextractor_proto_rawDescOnce.Do(func() {
		file_detailextractor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_detailextractor_proto_rawDesc), len(file_detailextractor_proto_rawDesc)))
	})
	return file_detailextractor_proto_rawDescData
}

var file_detailextractor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_detailextractor_proto_goTypes = []any{
	(*ExtractRequest)(nil),  // 0: smartfind.detailextractor.v1.ExtractRequest
	(*ExtractResponse)(nil), // 1: smartfind.detailextractor.v1.ExtractResponse
}
var file_detailextractor_proto_depIdxs = []int32{
	0, // 0: smartfind.detailextractor.v1.DetailExtractorService.Extract:input_type -> smartfind.detailextractor.v1.ExtractRequest
	1, // 1: smartfind.detailextractor.v1.DetailExtractorService.Extract:output_type -> smartfind.detailextractor.v1.ExtractResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_detailextractor_proto_init() }
func file_detailextractor_proto_init() {
	if File_detailextractor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_detailextractor_proto_rawDesc), len(file_detailextractor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_detailextractor_proto_goTypes,
		DependencyIndexes: file_detailextractor_proto_depIdxs,
		MessageInfos:      file_detailextractor_proto_msgTypes,
	}.Build()
	File_detailextractor_proto = out.File
	file_detailextractor_proto_goTypes = nil
	file_detailextractor_proto_depIdxs = nil
}
