// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: detailextractor.proto

package smartfindpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DetailExtractorService_Extract_FullMethodName = "/smartfind.detailextractor.v1.DetailExtractorService/Extract"
)

// DetailExtractorServiceClient is the client API for DetailExtractorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DetailExtractorServiceClient interface {
	Extract(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error)
}

type detailExtractorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDetailExtractorServiceClient(cc grpc.ClientConnInterface) DetailExtractorServiceClient {
	return &detailExtractorServiceClient{cc}
}

func (c *detailExtractorServiceClient) Extract(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractResponse)
	err := c.cc.Invoke(ctx, DetailExtractorService_Extract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DetailExtractorServiceServer is the server API for DetailExtractorService service.
// All implementations must embed UnimplementedDetailExtractorServiceServer
// for forward compatibility.
type DetailExtractorServiceServer interface {
	Extract(context.Context, *ExtractRequest) (*ExtractResponse, error)
	mustEmbedUnimplementedDetailExtractorServiceServer()
}

// UnimplementedDetailExtractorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDetailExtractorServiceServer struct{}

func (UnimplementedDetailExtractorServiceServer) Extract(context.Context, *ExtractRequest) (*ExtractResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Extract not implemented")
}
func (UnimplementedDetailExtractorServiceServer) mustEmbedUnimplementedDetailExtractorServiceServer() {
}
func (UnimplementedDetailExtractorServiceServer) testEmbeddedByValue() {}

// UnsafeDetailExtractorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DetailExtractorServiceServer will
// result in compilation errors.
type UnsafeDetailExtractorServiceServer interface {
	mustEmbedUnimplementedDetailExtractorServiceServer()
}

func RegisterDetailExtractorServiceServer(s grpc.ServiceRegistrar, srv DetailExtractorServiceServer) {
	// If the following call panics, it indicates UnimplementedDetailExtractorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DetailExtractorService_ServiceDesc, srv)
}

func _DetailExtractorService_Extract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetailExtractorServiceServer).Extract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetailExtractorService_Extract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetailExtractorServiceServer).Extract(ctx, req.(*ExtractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DetailExtractorService_ServiceDesc is the grpc.ServiceDesc for DetailExtractorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DetailExtractorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smartfind.detailextractor.v1.DetailExtractorService",
	HandlerType: (*DetailExtractorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Extract",
			Handler:    _DetailExtractorService_Extract_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "detailextractor.proto",
}
