# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import staff_pb2 as staff__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in staff_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StaffServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/smartfind.staff.v1.StaffService/Login',
                request_serializer=staff__pb2.LoginRequest.SerializeToString,
                response_deserializer=staff__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.CreateStaff = channel.unary_unary(
                '/smartfind.staff.v1.StaffService/CreateStaff',
                request_serializer=staff__pb2.CreateStaffRequest.SerializeToString,
                response_deserializer=staff__pb2.Staff.FromString,
                _registered_method=True)
        self.CreateFoundItem = channel.unary_unary(
                '/smartfind.staff.v1.StaffService/CreateFoundItem',
                request_serializer=staff__pb2.CreateFoundItemRequest.SerializeToString,
                response_deserializer=staff__pb2.FoundItem.FromString,
                _registered_method=True)
        self.UpdateFoundItemStatus = channel.unary_unary(
                '/smartfind.staff.v1.StaffService/UpdateFoundItemStatus',
                request_serializer=staff__pb2.UpdateFoundItemStatusRequest.SerializeToString,
                response_deserializer=staff__pb2.FoundItem.FromString,
                _registered_method=True)
        self.ListFoundItems = channel.unary_unary(
                '/smartfind.staff.v1.StaffService/ListFoundItems',
                request_serializer=staff__pb2.ListFoundItemsRequest.SerializeToString,
                response_deserializer=staff__pb2.ListFoundItemsResponse.FromString,
                _registered_method=True)
        self.InitFoundItemImageUploads = channel.unary_unary(
                '/smartfind.staff.v1.StaffService/InitFoundItemImageUploads',
                request_serializer=staff__pb2.InitFoundItemImageUploadsRequest.SerializeToString,
                response_deserializer=staff__pb2.InitFoundItemImageUploadsResponse.FromString,
                _registered_method=True)
        self.DeleteFoundItemImageUpload = channel.unary_unary(
                '/smartfind.staff.v1.StaffService/DeleteFoundItemImageUpload',
                request_serializer=staff__pb2.DeleteFoundItemImageUploadRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SearchFoundItemMatchesByEmbedding = channel.unary_unary(
                '/smartfind.staff.v1.StaffService/SearchFoundItemMatchesByEmbedding',
                request_serializer=staff__pb2.SearchFoundItemMatchesByEmbeddingRequest.SerializeToString,
                response_deserializer=staff__pb2.SearchFoundItemMatchesByEmbeddingResponse.FromString,
                _registered_method=True)
        self.ListClaims = channel.unary_unary(
                '/smartfind.staff.v1.StaffService/ListClaims',
                request_serializer=staff__pb2.ListClaimsRequest.SerializeToString,
                response_deserializer=staff__pb2.ListClaimsResponse.FromString,
                _registered_method=True)
        self.ReviewClaim = channel.unary_unary(
                '/smartfind.staff.v1.StaffService/ReviewClaim',
                request_serializer=staff__pb2.ReviewClaimRequest.SerializeToString,
                response_deserializer=staff__pb2.ItemClaim.FromString,
                _registered_method=True)
        self.CreateRoute = channel.unary_unary(
                '/smartfind.staff.v1.StaffService/CreateRoute',
                request_serializer=staff__pb2.CreateRouteRequest.SerializeToString,
                response_deserializer=staff__pb2.Route.FromString,
                _registered_method=True)
        self.DeleteRoute = channel.unary_unary(
                '/smartfind.staff.v1.StaffService/DeleteRoute',
                request_serializer=staff__pb2.DeleteRouteRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListRoutes = channel.unary_unary(
                '/smartfind.staff.v1.StaffService/ListRoutes',
                request_serializer=staff__pb2.ListRoutesRequest.SerializeToString,
                response_deserializer=staff__pb2.ListRoutesResponse.FromString,
                _registered_method=True)


class StaffServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateStaff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFoundItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFoundItemStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFoundItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitFoundItemImageUploads(self, request, context):
        """Media: found-item image uploads (S3 presigned URLs + cleanup).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFoundItemImageUpload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchFoundItemMatchesByEmbedding(self, request, context):
        """Internal-only: similarity search over found items using a query embedding.
        Auth: requires x-internal-token; does NOT require x-forwarded-token.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListClaims(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReviewClaim(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRoutes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StaffServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=staff__pb2.LoginRequest.FromString,
                    response_serializer=staff__pb2.LoginResponse.SerializeToString,
            ),
            'CreateStaff': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateStaff,
                    request_deserializer=staff__pb2.CreateStaffRequest.FromString,
                    response_serializer=staff__pb2.Staff.SerializeToString,
            ),
            'CreateFoundItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFoundItem,
                    request_deserializer=staff__pb2.CreateFoundItemRequest.FromString,
                    response_serializer=staff__pb2.FoundItem.SerializeToString,
            ),
            'UpdateFoundItemStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFoundItemStatus,
                    request_deserializer=staff__pb2.UpdateFoundItemStatusRequest.FromString,
                    response_serializer=staff__pb2.FoundItem.SerializeToString,
            ),
            'ListFoundItems': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFoundItems,
                    request_deserializer=staff__pb2.ListFoundItemsRequest.FromString,
                    response_serializer=staff__pb2.ListFoundItemsResponse.SerializeToString,
            ),
            'InitFoundItemImageUploads': grpc.unary_unary_rpc_method_handler(
                    servicer.InitFoundItemImageUploads,
                    request_deserializer=staff__pb2.InitFoundItemImageUploadsRequest.FromString,
                    response_serializer=staff__pb2.InitFoundItemImageUploadsResponse.SerializeToString,
            ),
            'DeleteFoundItemImageUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFoundItemImageUpload,
                    request_deserializer=staff__pb2.DeleteFoundItemImageUploadRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SearchFoundItemMatchesByEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchFoundItemMatchesByEmbedding,
                    request_deserializer=staff__pb2.SearchFoundItemMatchesByEmbeddingRequest.FromString,
                    response_serializer=staff__pb2.SearchFoundItemMatchesByEmbeddingResponse.SerializeToString,
            ),
            'ListClaims': grpc.unary_unary_rpc_method_handler(
                    servicer.ListClaims,
                    request_deserializer=staff__pb2.ListClaimsRequest.FromString,
                    response_serializer=staff__pb2.ListClaimsResponse.SerializeToString,
            ),
            'ReviewClaim': grpc.unary_unary_rpc_method_handler(
                    servicer.ReviewClaim,
                    request_deserializer=staff__pb2.ReviewClaimRequest.FromString,
                    response_serializer=staff__pb2.ItemClaim.SerializeToString,
            ),
            'CreateRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRoute,
                    request_deserializer=staff__pb2.CreateRouteRequest.FromString,
                    response_serializer=staff__pb2.Route.SerializeToString,
            ),
            'DeleteRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRoute,
                    request_deserializer=staff__pb2.DeleteRouteRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListRoutes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRoutes,
                    request_deserializer=staff__pb2.ListRoutesRequest.FromString,
                    response_serializer=staff__pb2.ListRoutesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'smartfind.staff.v1.StaffService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('smartfind.staff.v1.StaffService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StaffService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartfind.staff.v1.StaffService/Login',
            staff__pb2.LoginRequest.SerializeToString,
            staff__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateStaff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartfind.staff.v1.StaffService/CreateStaff',
            staff__pb2.CreateStaffRequest.SerializeToString,
            staff__pb2.Staff.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateFoundItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartfind.staff.v1.StaffService/CreateFoundItem',
            staff__pb2.CreateFoundItemRequest.SerializeToString,
            staff__pb2.FoundItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateFoundItemStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartfind.staff.v1.StaffService/UpdateFoundItemStatus',
            staff__pb2.UpdateFoundItemStatusRequest.SerializeToString,
            staff__pb2.FoundItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFoundItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartfind.staff.v1.StaffService/ListFoundItems',
            staff__pb2.ListFoundItemsRequest.SerializeToString,
            staff__pb2.ListFoundItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitFoundItemImageUploads(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartfind.staff.v1.StaffService/InitFoundItemImageUploads',
            staff__pb2.InitFoundItemImageUploadsRequest.SerializeToString,
            staff__pb2.InitFoundItemImageUploadsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFoundItemImageUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartfind.staff.v1.StaffService/DeleteFoundItemImageUpload',
            staff__pb2.DeleteFoundItemImageUploadRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchFoundItemMatchesByEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartfind.staff.v1.StaffService/SearchFoundItemMatchesByEmbedding',
            staff__pb2.SearchFoundItemMatchesByEmbeddingRequest.SerializeToString,
            staff__pb2.SearchFoundItemMatchesByEmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListClaims(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartfind.staff.v1.StaffService/ListClaims',
            staff__pb2.ListClaimsRequest.SerializeToString,
            staff__pb2.ListClaimsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReviewClaim(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartfind.staff.v1.StaffService/ReviewClaim',
            staff__pb2.ReviewClaimRequest.SerializeToString,
            staff__pb2.ItemClaim.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartfind.staff.v1.StaffService/CreateRoute',
            staff__pb2.CreateRouteRequest.SerializeToString,
            staff__pb2.Route.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartfind.staff.v1.StaffService/DeleteRoute',
            staff__pb2.DeleteRouteRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRoutes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartfind.staff.v1.StaffService/ListRoutes',
            staff__pb2.ListRoutesRequest.SerializeToString,
            staff__pb2.ListRoutesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
