# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import passenger_pb2 as passenger__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in passenger_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PassengerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/smartfind.passenger.v1.PassengerService/Login',
                request_serializer=passenger__pb2.LoginRequest.SerializeToString,
                response_deserializer=passenger__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/smartfind.passenger.v1.PassengerService/Logout',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CreateLostReport = channel.unary_unary(
                '/smartfind.passenger.v1.PassengerService/CreateLostReport',
                request_serializer=passenger__pb2.CreateLostReportRequest.SerializeToString,
                response_deserializer=passenger__pb2.LostReport.FromString,
                _registered_method=True)
        self.ListLostReports = channel.unary_unary(
                '/smartfind.passenger.v1.PassengerService/ListLostReports',
                request_serializer=passenger__pb2.ListLostReportsRequest.SerializeToString,
                response_deserializer=passenger__pb2.ListLostReportsResponse.FromString,
                _registered_method=True)
        self.DeleteLostReport = channel.unary_unary(
                '/smartfind.passenger.v1.PassengerService/DeleteLostReport',
                request_serializer=passenger__pb2.DeleteLostReportRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SearchFoundItemMatches = channel.unary_unary(
                '/smartfind.passenger.v1.PassengerService/SearchFoundItemMatches',
                request_serializer=passenger__pb2.SearchFoundItemMatchesRequest.SerializeToString,
                response_deserializer=passenger__pb2.SearchFoundItemMatchesResponse.FromString,
                _registered_method=True)
        self.FileClaim = channel.unary_unary(
                '/smartfind.passenger.v1.PassengerService/FileClaim',
                request_serializer=passenger__pb2.FileClaimRequest.SerializeToString,
                response_deserializer=passenger__pb2.ItemClaim.FromString,
                _registered_method=True)


class PassengerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateLostReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLostReports(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteLostReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchFoundItemMatches(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileClaim(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PassengerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=passenger__pb2.LoginRequest.FromString,
                    response_serializer=passenger__pb2.LoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CreateLostReport': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLostReport,
                    request_deserializer=passenger__pb2.CreateLostReportRequest.FromString,
                    response_serializer=passenger__pb2.LostReport.SerializeToString,
            ),
            'ListLostReports': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLostReports,
                    request_deserializer=passenger__pb2.ListLostReportsRequest.FromString,
                    response_serializer=passenger__pb2.ListLostReportsResponse.SerializeToString,
            ),
            'DeleteLostReport': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteLostReport,
                    request_deserializer=passenger__pb2.DeleteLostReportRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SearchFoundItemMatches': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchFoundItemMatches,
                    request_deserializer=passenger__pb2.SearchFoundItemMatchesRequest.FromString,
                    response_serializer=passenger__pb2.SearchFoundItemMatchesResponse.SerializeToString,
            ),
            'FileClaim': grpc.unary_unary_rpc_method_handler(
                    servicer.FileClaim,
                    request_deserializer=passenger__pb2.FileClaimRequest.FromString,
                    response_serializer=passenger__pb2.ItemClaim.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'smartfind.passenger.v1.PassengerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('smartfind.passenger.v1.PassengerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PassengerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartfind.passenger.v1.PassengerService/Login',
            passenger__pb2.LoginRequest.SerializeToString,
            passenger__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartfind.passenger.v1.PassengerService/Logout',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateLostReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartfind.passenger.v1.PassengerService/CreateLostReport',
            passenger__pb2.CreateLostReportRequest.SerializeToString,
            passenger__pb2.LostReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLostReports(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartfind.passenger.v1.PassengerService/ListLostReports',
            passenger__pb2.ListLostReportsRequest.SerializeToString,
            passenger__pb2.ListLostReportsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteLostReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartfind.passenger.v1.PassengerService/DeleteLostReport',
            passenger__pb2.DeleteLostReportRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchFoundItemMatches(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartfind.passenger.v1.PassengerService/SearchFoundItemMatches',
            passenger__pb2.SearchFoundItemMatchesRequest.SerializeToString,
            passenger__pb2.SearchFoundItemMatchesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileClaim(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smartfind.passenger.v1.PassengerService/FileClaim',
            passenger__pb2.FileClaimRequest.SerializeToString,
            passenger__pb2.ItemClaim.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
