// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.4
// source: staff.proto

package smartfindpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Staff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Staff) Reset() {
	*x = Staff{}
	mi := &file_staff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Staff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Staff) ProtoMessage() {}

func (x *Staff) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Staff.ProtoReflect.Descriptor instead.
func (*Staff) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{0}
}

func (x *Staff) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Staff) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Staff) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Staff) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Staff) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_staff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Staff         *Staff                 `protobuf:"bytes,1,opt,name=staff,proto3" json:"staff,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_staff_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResponse) GetStaff() *Staff {
	if x != nil {
		return x.Staff
	}
	return nil
}

func (x *LoginResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type CreateStaffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransitCode   string                 `protobuf:"bytes,1,opt,name=transit_code,json=transitCode,proto3" json:"transit_code,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStaffRequest) Reset() {
	*x = CreateStaffRequest{}
	mi := &file_staff_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStaffRequest) ProtoMessage() {}

func (x *CreateStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStaffRequest.ProtoReflect.Descriptor instead.
func (*CreateStaffRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{3}
}

func (x *CreateStaffRequest) GetTransitCode() string {
	if x != nil {
		return x.TransitCode
	}
	return ""
}

func (x *CreateStaffRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateStaffRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateStaffRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type FoundItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PostedByStaffId string                 `protobuf:"bytes,2,opt,name=posted_by_staff_id,json=postedByStaffId,proto3" json:"posted_by_staff_id,omitempty"`
	ItemName        string                 `protobuf:"bytes,3,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	ItemDescription string                 `protobuf:"bytes,4,opt,name=item_description,json=itemDescription,proto3" json:"item_description,omitempty"`
	ItemType        string                 `protobuf:"bytes,5,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	Brand           string                 `protobuf:"bytes,6,opt,name=brand,proto3" json:"brand,omitempty"`
	Model           string                 `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`
	Color           string                 `protobuf:"bytes,8,opt,name=color,proto3" json:"color,omitempty"`
	Material        string                 `protobuf:"bytes,9,opt,name=material,proto3" json:"material,omitempty"`
	ItemCondition   string                 `protobuf:"bytes,10,opt,name=item_condition,json=itemCondition,proto3" json:"item_condition,omitempty"`
	Category        string                 `protobuf:"bytes,11,opt,name=category,proto3" json:"category,omitempty"`
	LocationFound   string                 `protobuf:"bytes,12,opt,name=location_found,json=locationFound,proto3" json:"location_found,omitempty"`
	RouteOrStation  string                 `protobuf:"bytes,13,opt,name=route_or_station,json=routeOrStation,proto3" json:"route_or_station,omitempty"`
	RouteId         string                 `protobuf:"bytes,14,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	DateFound       *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_found,json=dateFound,proto3" json:"date_found,omitempty"`
	Status          string                 `protobuf:"bytes,16,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ImageKeys       []string               `protobuf:"bytes,19,rep,name=image_keys,json=imageKeys,proto3" json:"image_keys,omitempty"`
	PrimaryImageKey string                 `protobuf:"bytes,20,opt,name=primary_image_key,json=primaryImageKey,proto3" json:"primary_image_key,omitempty"`
	// Presigned GET URLs for displaying images in the dashboard.
	ImageUrls       []string `protobuf:"bytes,21,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	PrimaryImageUrl string   `protobuf:"bytes,22,opt,name=primary_image_url,json=primaryImageUrl,proto3" json:"primary_image_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FoundItem) Reset() {
	*x = FoundItem{}
	mi := &file_staff_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoundItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoundItem) ProtoMessage() {}

func (x *FoundItem) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoundItem.ProtoReflect.Descriptor instead.
func (*FoundItem) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{4}
}

func (x *FoundItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FoundItem) GetPostedByStaffId() string {
	if x != nil {
		return x.PostedByStaffId
	}
	return ""
}

func (x *FoundItem) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *FoundItem) GetItemDescription() string {
	if x != nil {
		return x.ItemDescription
	}
	return ""
}

func (x *FoundItem) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *FoundItem) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *FoundItem) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *FoundItem) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *FoundItem) GetMaterial() string {
	if x != nil {
		return x.Material
	}
	return ""
}

func (x *FoundItem) GetItemCondition() string {
	if x != nil {
		return x.ItemCondition
	}
	return ""
}

func (x *FoundItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *FoundItem) GetLocationFound() string {
	if x != nil {
		return x.LocationFound
	}
	return ""
}

func (x *FoundItem) GetRouteOrStation() string {
	if x != nil {
		return x.RouteOrStation
	}
	return ""
}

func (x *FoundItem) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *FoundItem) GetDateFound() *timestamppb.Timestamp {
	if x != nil {
		return x.DateFound
	}
	return nil
}

func (x *FoundItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FoundItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FoundItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *FoundItem) GetImageKeys() []string {
	if x != nil {
		return x.ImageKeys
	}
	return nil
}

func (x *FoundItem) GetPrimaryImageKey() string {
	if x != nil {
		return x.PrimaryImageKey
	}
	return ""
}

func (x *FoundItem) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *FoundItem) GetPrimaryImageUrl() string {
	if x != nil {
		return x.PrimaryImageUrl
	}
	return ""
}

type CreateFoundItemRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StaffId         string                 `protobuf:"bytes,1,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	ItemName        string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	ItemDescription string                 `protobuf:"bytes,3,opt,name=item_description,json=itemDescription,proto3" json:"item_description,omitempty"`
	ItemType        string                 `protobuf:"bytes,4,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	Brand           string                 `protobuf:"bytes,5,opt,name=brand,proto3" json:"brand,omitempty"`
	Model           string                 `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	Color           string                 `protobuf:"bytes,7,opt,name=color,proto3" json:"color,omitempty"`
	Material        string                 `protobuf:"bytes,8,opt,name=material,proto3" json:"material,omitempty"`
	ItemCondition   string                 `protobuf:"bytes,9,opt,name=item_condition,json=itemCondition,proto3" json:"item_condition,omitempty"`
	Category        string                 `protobuf:"bytes,10,opt,name=category,proto3" json:"category,omitempty"`
	LocationFound   string                 `protobuf:"bytes,11,opt,name=location_found,json=locationFound,proto3" json:"location_found,omitempty"`
	RouteOrStation  string                 `protobuf:"bytes,12,opt,name=route_or_station,json=routeOrStation,proto3" json:"route_or_station,omitempty"`
	RouteId         string                 `protobuf:"bytes,13,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	DateFound       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=date_found,json=dateFound,proto3" json:"date_found,omitempty"`
	ImageKeys       []string               `protobuf:"bytes,15,rep,name=image_keys,json=imageKeys,proto3" json:"image_keys,omitempty"`
	PrimaryImageKey string                 `protobuf:"bytes,16,opt,name=primary_image_key,json=primaryImageKey,proto3" json:"primary_image_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateFoundItemRequest) Reset() {
	*x = CreateFoundItemRequest{}
	mi := &file_staff_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFoundItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFoundItemRequest) ProtoMessage() {}

func (x *CreateFoundItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFoundItemRequest.ProtoReflect.Descriptor instead.
func (*CreateFoundItemRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{5}
}

func (x *CreateFoundItemRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *CreateFoundItemRequest) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *CreateFoundItemRequest) GetItemDescription() string {
	if x != nil {
		return x.ItemDescription
	}
	return ""
}

func (x *CreateFoundItemRequest) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *CreateFoundItemRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CreateFoundItemRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateFoundItemRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *CreateFoundItemRequest) GetMaterial() string {
	if x != nil {
		return x.Material
	}
	return ""
}

func (x *CreateFoundItemRequest) GetItemCondition() string {
	if x != nil {
		return x.ItemCondition
	}
	return ""
}

func (x *CreateFoundItemRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateFoundItemRequest) GetLocationFound() string {
	if x != nil {
		return x.LocationFound
	}
	return ""
}

func (x *CreateFoundItemRequest) GetRouteOrStation() string {
	if x != nil {
		return x.RouteOrStation
	}
	return ""
}

func (x *CreateFoundItemRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *CreateFoundItemRequest) GetDateFound() *timestamppb.Timestamp {
	if x != nil {
		return x.DateFound
	}
	return nil
}

func (x *CreateFoundItemRequest) GetImageKeys() []string {
	if x != nil {
		return x.ImageKeys
	}
	return nil
}

func (x *CreateFoundItemRequest) GetPrimaryImageKey() string {
	if x != nil {
		return x.PrimaryImageKey
	}
	return ""
}

type InitFoundItemImageUploadsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*UploadFile          `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitFoundItemImageUploadsRequest) Reset() {
	*x = InitFoundItemImageUploadsRequest{}
	mi := &file_staff_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitFoundItemImageUploadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitFoundItemImageUploadsRequest) ProtoMessage() {}

func (x *InitFoundItemImageUploadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitFoundItemImageUploadsRequest.ProtoReflect.Descriptor instead.
func (*InitFoundItemImageUploadsRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{6}
}

func (x *InitFoundItemImageUploadsRequest) GetFiles() []*UploadFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type UploadFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   string                 `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFile) Reset() {
	*x = UploadFile{}
	mi := &file_staff_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFile) ProtoMessage() {}

func (x *UploadFile) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFile.ProtoReflect.Descriptor instead.
func (*UploadFile) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{7}
}

func (x *UploadFile) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadFile) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type InitFoundItemImageUploadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uploads       []*UploadInit          `protobuf:"bytes,1,rep,name=uploads,proto3" json:"uploads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitFoundItemImageUploadsResponse) Reset() {
	*x = InitFoundItemImageUploadsResponse{}
	mi := &file_staff_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitFoundItemImageUploadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitFoundItemImageUploadsResponse) ProtoMessage() {}

func (x *InitFoundItemImageUploadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitFoundItemImageUploadsResponse.ProtoReflect.Descriptor instead.
func (*InitFoundItemImageUploadsResponse) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{8}
}

func (x *InitFoundItemImageUploadsResponse) GetUploads() []*UploadInit {
	if x != nil {
		return x.Uploads
	}
	return nil
}

type UploadInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	S3Key         string                 `protobuf:"bytes,1,opt,name=s3_key,json=s3Key,proto3" json:"s3_key,omitempty"`
	UploadUrl     string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadInit) Reset() {
	*x = UploadInit{}
	mi := &file_staff_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadInit) ProtoMessage() {}

func (x *UploadInit) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadInit.ProtoReflect.Descriptor instead.
func (*UploadInit) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{9}
}

func (x *UploadInit) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

func (x *UploadInit) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *UploadInit) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type DeleteFoundItemImageUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	S3Key         string                 `protobuf:"bytes,1,opt,name=s3_key,json=s3Key,proto3" json:"s3_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFoundItemImageUploadRequest) Reset() {
	*x = DeleteFoundItemImageUploadRequest{}
	mi := &file_staff_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFoundItemImageUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFoundItemImageUploadRequest) ProtoMessage() {}

func (x *DeleteFoundItemImageUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFoundItemImageUploadRequest.ProtoReflect.Descriptor instead.
func (*DeleteFoundItemImageUploadRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteFoundItemImageUploadRequest) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

type SearchFoundItemMatchesByEmbeddingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QueryEmbedding []float32              `protobuf:"fixed32,1,rep,packed,name=query_embedding,json=queryEmbedding,proto3" json:"query_embedding,omitempty"`
	Limit          int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	MinSimilarity  float64                `protobuf:"fixed64,3,opt,name=min_similarity,json=minSimilarity,proto3" json:"min_similarity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchFoundItemMatchesByEmbeddingRequest) Reset() {
	*x = SearchFoundItemMatchesByEmbeddingRequest{}
	mi := &file_staff_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFoundItemMatchesByEmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFoundItemMatchesByEmbeddingRequest) ProtoMessage() {}

func (x *SearchFoundItemMatchesByEmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFoundItemMatchesByEmbeddingRequest.ProtoReflect.Descriptor instead.
func (*SearchFoundItemMatchesByEmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{11}
}

func (x *SearchFoundItemMatchesByEmbeddingRequest) GetQueryEmbedding() []float32 {
	if x != nil {
		return x.QueryEmbedding
	}
	return nil
}

func (x *SearchFoundItemMatchesByEmbeddingRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchFoundItemMatchesByEmbeddingRequest) GetMinSimilarity() float64 {
	if x != nil {
		return x.MinSimilarity
	}
	return 0
}

type SearchFoundItemMatchesByEmbeddingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*FoundItemMatch      `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFoundItemMatchesByEmbeddingResponse) Reset() {
	*x = SearchFoundItemMatchesByEmbeddingResponse{}
	mi := &file_staff_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFoundItemMatchesByEmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFoundItemMatchesByEmbeddingResponse) ProtoMessage() {}

func (x *SearchFoundItemMatchesByEmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFoundItemMatchesByEmbeddingResponse.ProtoReflect.Descriptor instead.
func (*SearchFoundItemMatchesByEmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{12}
}

func (x *SearchFoundItemMatchesByEmbeddingResponse) GetMatches() []*FoundItemMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

type FoundItemMatch struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Item            *FoundItem             `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	SimilarityScore float64                `protobuf:"fixed64,2,opt,name=similarity_score,json=similarityScore,proto3" json:"similarity_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FoundItemMatch) Reset() {
	*x = FoundItemMatch{}
	mi := &file_staff_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoundItemMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoundItemMatch) ProtoMessage() {}

func (x *FoundItemMatch) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoundItemMatch.ProtoReflect.Descriptor instead.
func (*FoundItemMatch) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{13}
}

func (x *FoundItemMatch) GetItem() *FoundItem {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *FoundItemMatch) GetSimilarityScore() float64 {
	if x != nil {
		return x.SimilarityScore
	}
	return 0
}

type UpdateFoundItemStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StaffId       string                 `protobuf:"bytes,1,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	FoundItemId   string                 `protobuf:"bytes,2,opt,name=found_item_id,json=foundItemId,proto3" json:"found_item_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFoundItemStatusRequest) Reset() {
	*x = UpdateFoundItemStatusRequest{}
	mi := &file_staff_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFoundItemStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFoundItemStatusRequest) ProtoMessage() {}

func (x *UpdateFoundItemStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFoundItemStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateFoundItemStatusRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateFoundItemStatusRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *UpdateFoundItemStatusRequest) GetFoundItemId() string {
	if x != nil {
		return x.FoundItemId
	}
	return ""
}

func (x *UpdateFoundItemStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListFoundItemsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	RouteId         string                 `protobuf:"bytes,2,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	PostedByStaffId string                 `protobuf:"bytes,3,opt,name=posted_by_staff_id,json=postedByStaffId,proto3" json:"posted_by_staff_id,omitempty"`
	Limit           int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset          int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListFoundItemsRequest) Reset() {
	*x = ListFoundItemsRequest{}
	mi := &file_staff_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFoundItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoundItemsRequest) ProtoMessage() {}

func (x *ListFoundItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoundItemsRequest.ProtoReflect.Descriptor instead.
func (*ListFoundItemsRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{15}
}

func (x *ListFoundItemsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListFoundItemsRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *ListFoundItemsRequest) GetPostedByStaffId() string {
	if x != nil {
		return x.PostedByStaffId
	}
	return ""
}

func (x *ListFoundItemsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListFoundItemsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListFoundItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FoundItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFoundItemsResponse) Reset() {
	*x = ListFoundItemsResponse{}
	mi := &file_staff_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFoundItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoundItemsResponse) ProtoMessage() {}

func (x *ListFoundItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoundItemsResponse.ProtoReflect.Descriptor instead.
func (*ListFoundItemsResponse) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{16}
}

func (x *ListFoundItemsResponse) GetItems() []*FoundItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ItemClaim struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemId              string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ClaimantPassengerId string                 `protobuf:"bytes,3,opt,name=claimant_passenger_id,json=claimantPassengerId,proto3" json:"claimant_passenger_id,omitempty"`
	LostReportId        string                 `protobuf:"bytes,4,opt,name=lost_report_id,json=lostReportId,proto3" json:"lost_report_id,omitempty"`
	Message             string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Status              string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ItemClaim) Reset() {
	*x = ItemClaim{}
	mi := &file_staff_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemClaim) ProtoMessage() {}

func (x *ItemClaim) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemClaim.ProtoReflect.Descriptor instead.
func (*ItemClaim) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{17}
}

func (x *ItemClaim) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemClaim) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ItemClaim) GetClaimantPassengerId() string {
	if x != nil {
		return x.ClaimantPassengerId
	}
	return ""
}

func (x *ItemClaim) GetLostReportId() string {
	if x != nil {
		return x.LostReportId
	}
	return ""
}

func (x *ItemClaim) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ItemClaim) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ItemClaim) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ItemClaim) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListClaimsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	PassengerId   string                 `protobuf:"bytes,3,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClaimsRequest) Reset() {
	*x = ListClaimsRequest{}
	mi := &file_staff_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClaimsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClaimsRequest) ProtoMessage() {}

func (x *ListClaimsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClaimsRequest.ProtoReflect.Descriptor instead.
func (*ListClaimsRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{18}
}

func (x *ListClaimsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListClaimsRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ListClaimsRequest) GetPassengerId() string {
	if x != nil {
		return x.PassengerId
	}
	return ""
}

func (x *ListClaimsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListClaimsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListClaimsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claims        []*ItemClaim           `protobuf:"bytes,1,rep,name=claims,proto3" json:"claims,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClaimsResponse) Reset() {
	*x = ListClaimsResponse{}
	mi := &file_staff_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClaimsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClaimsResponse) ProtoMessage() {}

func (x *ListClaimsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClaimsResponse.ProtoReflect.Descriptor instead.
func (*ListClaimsResponse) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{19}
}

func (x *ListClaimsResponse) GetClaims() []*ItemClaim {
	if x != nil {
		return x.Claims
	}
	return nil
}

type ReviewClaimRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StaffId       string                 `protobuf:"bytes,1,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	ClaimId       string                 `protobuf:"bytes,2,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	Decision      string                 `protobuf:"bytes,3,opt,name=decision,proto3" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewClaimRequest) Reset() {
	*x = ReviewClaimRequest{}
	mi := &file_staff_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewClaimRequest) ProtoMessage() {}

func (x *ReviewClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewClaimRequest.ProtoReflect.Descriptor instead.
func (*ReviewClaimRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{20}
}

func (x *ReviewClaimRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *ReviewClaimRequest) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *ReviewClaimRequest) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

type Route struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RouteName        string                 `protobuf:"bytes,2,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`
	CreatedByStaffId string                 `protobuf:"bytes,3,opt,name=created_by_staff_id,json=createdByStaffId,proto3" json:"created_by_staff_id,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_staff_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{21}
}

func (x *Route) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Route) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

func (x *Route) GetCreatedByStaffId() string {
	if x != nil {
		return x.CreatedByStaffId
	}
	return ""
}

func (x *Route) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Route) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StaffId       string                 `protobuf:"bytes,1,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	RouteName     string                 `protobuf:"bytes,2,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRouteRequest) Reset() {
	*x = CreateRouteRequest{}
	mi := &file_staff_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRouteRequest) ProtoMessage() {}

func (x *CreateRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRouteRequest.ProtoReflect.Descriptor instead.
func (*CreateRouteRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{22}
}

func (x *CreateRouteRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *CreateRouteRequest) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

type DeleteRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StaffId       string                 `protobuf:"bytes,1,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	RouteId       string                 `protobuf:"bytes,2,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRouteRequest) Reset() {
	*x = DeleteRouteRequest{}
	mi := &file_staff_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRouteRequest) ProtoMessage() {}

func (x *DeleteRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRouteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRouteRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteRouteRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *DeleteRouteRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

type ListRoutesRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CreatedByStaffId string                 `protobuf:"bytes,1,opt,name=created_by_staff_id,json=createdByStaffId,proto3" json:"created_by_staff_id,omitempty"`
	Limit            int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset           int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListRoutesRequest) Reset() {
	*x = ListRoutesRequest{}
	mi := &file_staff_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesRequest) ProtoMessage() {}

func (x *ListRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesRequest.ProtoReflect.Descriptor instead.
func (*ListRoutesRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{24}
}

func (x *ListRoutesRequest) GetCreatedByStaffId() string {
	if x != nil {
		return x.CreatedByStaffId
	}
	return ""
}

func (x *ListRoutesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRoutesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*Route               `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesResponse) Reset() {
	*x = ListRoutesResponse{}
	mi := &file_staff_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesResponse) ProtoMessage() {}

func (x *ListRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesResponse.ProtoReflect.Descriptor instead.
func (*ListRoutesResponse) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{25}
}

func (x *ListRoutesResponse) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

var File_staff_proto protoreflect.FileDescriptor

const file_staff_proto_rawDesc = "" +
	"\n" +
	"\vstaff.proto\x12\x12smartfind.staff.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc0\x01\n" +
	"\x05Staff\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"e\n" +
	"\rLoginResponse\x12/\n" +
	"\x05staff\x18\x01 \x01(\v2\x19.smartfind.staff.v1.StaffR\x05staff\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\"\x86\x01\n" +
	"\x12CreateStaffRequest\x12!\n" +
	"\ftransit_code\x18\x01 \x01(\tR\vtransitCode\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"\x99\x06\n" +
	"\tFoundItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x12posted_by_staff_id\x18\x02 \x01(\tR\x0fpostedByStaffId\x12\x1b\n" +
	"\titem_name\x18\x03 \x01(\tR\bitemName\x12)\n" +
	"\x10item_description\x18\x04 \x01(\tR\x0fitemDescription\x12\x1b\n" +
	"\titem_type\x18\x05 \x01(\tR\bitemType\x12\x14\n" +
	"\x05brand\x18\x06 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\a \x01(\tR\x05model\x12\x14\n" +
	"\x05color\x18\b \x01(\tR\x05color\x12\x1a\n" +
	"\bmaterial\x18\t \x01(\tR\bmaterial\x12%\n" +
	"\x0eitem_condition\x18\n" +
	" \x01(\tR\ritemCondition\x12\x1a\n" +
	"\bcategory\x18\v \x01(\tR\bcategory\x12%\n" +
	"\x0elocation_found\x18\f \x01(\tR\rlocationFound\x12(\n" +
	"\x10route_or_station\x18\r \x01(\tR\x0erouteOrStation\x12\x19\n" +
	"\broute_id\x18\x0e \x01(\tR\arouteId\x129\n" +
	"\n" +
	"date_found\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tdateFound\x12\x16\n" +
	"\x06status\x18\x10 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"image_keys\x18\x13 \x03(\tR\timageKeys\x12*\n" +
	"\x11primary_image_key\x18\x14 \x01(\tR\x0fprimaryImageKey\x12\x1d\n" +
	"\n" +
	"image_urls\x18\x15 \x03(\tR\timageUrls\x12*\n" +
	"\x11primary_image_url\x18\x16 \x01(\tR\x0fprimaryImageUrl\"\xab\x04\n" +
	"\x16CreateFoundItemRequest\x12\x19\n" +
	"\bstaff_id\x18\x01 \x01(\tR\astaffId\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12)\n" +
	"\x10item_description\x18\x03 \x01(\tR\x0fitemDescription\x12\x1b\n" +
	"\titem_type\x18\x04 \x01(\tR\bitemType\x12\x14\n" +
	"\x05brand\x18\x05 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x06 \x01(\tR\x05model\x12\x14\n" +
	"\x05color\x18\a \x01(\tR\x05color\x12\x1a\n" +
	"\bmaterial\x18\b \x01(\tR\bmaterial\x12%\n" +
	"\x0eitem_condition\x18\t \x01(\tR\ritemCondition\x12\x1a\n" +
	"\bcategory\x18\n" +
	" \x01(\tR\bcategory\x12%\n" +
	"\x0elocation_found\x18\v \x01(\tR\rlocationFound\x12(\n" +
	"\x10route_or_station\x18\f \x01(\tR\x0erouteOrStation\x12\x19\n" +
	"\broute_id\x18\r \x01(\tR\arouteId\x129\n" +
	"\n" +
	"date_found\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tdateFound\x12\x1d\n" +
	"\n" +
	"image_keys\x18\x0f \x03(\tR\timageKeys\x12*\n" +
	"\x11primary_image_key\x18\x10 \x01(\tR\x0fprimaryImageKey\"X\n" +
	" InitFoundItemImageUploadsRequest\x124\n" +
	"\x05files\x18\x01 \x03(\v2\x1e.smartfind.staff.v1.UploadFileR\x05files\"N\n" +
	"\n" +
	"UploadFile\x12!\n" +
	"\fcontent_type\x18\x01 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\"]\n" +
	"!InitFoundItemImageUploadsResponse\x128\n" +
	"\auploads\x18\x01 \x03(\v2\x1e.smartfind.staff.v1.UploadInitR\auploads\"\xc5\x01\n" +
	"\n" +
	"UploadInit\x12\x15\n" +
	"\x06s3_key\x18\x01 \x01(\tR\x05s3Key\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\x12E\n" +
	"\aheaders\x18\x03 \x03(\v2+.smartfind.staff.v1.UploadInit.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"!DeleteFoundItemImageUploadRequest\x12\x15\n" +
	"\x06s3_key\x18\x01 \x01(\tR\x05s3Key\"\x90\x01\n" +
	"(SearchFoundItemMatchesByEmbeddingRequest\x12'\n" +
	"\x0fquery_embedding\x18\x01 \x03(\x02R\x0equeryEmbedding\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12%\n" +
	"\x0emin_similarity\x18\x03 \x01(\x01R\rminSimilarity\"i\n" +
	")SearchFoundItemMatchesByEmbeddingResponse\x12<\n" +
	"\amatches\x18\x01 \x03(\v2\".smartfind.staff.v1.FoundItemMatchR\amatches\"n\n" +
	"\x0eFoundItemMatch\x121\n" +
	"\x04item\x18\x01 \x01(\v2\x1d.smartfind.staff.v1.FoundItemR\x04item\x12)\n" +
	"\x10similarity_score\x18\x02 \x01(\x01R\x0fsimilarityScore\"u\n" +
	"\x1cUpdateFoundItemStatusRequest\x12\x19\n" +
	"\bstaff_id\x18\x01 \x01(\tR\astaffId\x12\"\n" +
	"\rfound_item_id\x18\x02 \x01(\tR\vfoundItemId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xa5\x01\n" +
	"\x15ListFoundItemsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x19\n" +
	"\broute_id\x18\x02 \x01(\tR\arouteId\x12+\n" +
	"\x12posted_by_staff_id\x18\x03 \x01(\tR\x0fpostedByStaffId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"M\n" +
	"\x16ListFoundItemsResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.smartfind.staff.v1.FoundItemR\x05items\"\xb6\x02\n" +
	"\tItemClaim\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x122\n" +
	"\x15claimant_passenger_id\x18\x03 \x01(\tR\x13claimantPassengerId\x12$\n" +
	"\x0elost_report_id\x18\x04 \x01(\tR\flostReportId\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x95\x01\n" +
	"\x11ListClaimsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12!\n" +
	"\fpassenger_id\x18\x03 \x01(\tR\vpassengerId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"K\n" +
	"\x12ListClaimsResponse\x125\n" +
	"\x06claims\x18\x01 \x03(\v2\x1d.smartfind.staff.v1.ItemClaimR\x06claims\"f\n" +
	"\x12ReviewClaimRequest\x12\x19\n" +
	"\bstaff_id\x18\x01 \x01(\tR\astaffId\x12\x19\n" +
	"\bclaim_id\x18\x02 \x01(\tR\aclaimId\x12\x1a\n" +
	"\bdecision\x18\x03 \x01(\tR\bdecision\"\xdb\x01\n" +
	"\x05Route\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"route_name\x18\x02 \x01(\tR\trouteName\x12-\n" +
	"\x13created_by_staff_id\x18\x03 \x01(\tR\x10createdByStaffId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"N\n" +
	"\x12CreateRouteRequest\x12\x19\n" +
	"\bstaff_id\x18\x01 \x01(\tR\astaffId\x12\x1d\n" +
	"\n" +
	"route_name\x18\x02 \x01(\tR\trouteName\"J\n" +
	"\x12DeleteRouteRequest\x12\x19\n" +
	"\bstaff_id\x18\x01 \x01(\tR\astaffId\x12\x19\n" +
	"\broute_id\x18\x02 \x01(\tR\arouteId\"p\n" +
	"\x11ListRoutesRequest\x12-\n" +
	"\x13created_by_staff_id\x18\x01 \x01(\tR\x10createdByStaffId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"G\n" +
	"\x12ListRoutesResponse\x121\n" +
	"\x06routes\x18\x01 \x03(\v2\x19.smartfind.staff.v1.RouteR\x06routes2\xab\n" +
	"\n" +
	"\fStaffService\x12L\n" +
	"\x05Login\x12 .smartfind.staff.v1.LoginRequest\x1a!.smartfind.staff.v1.LoginResponse\x12P\n" +
	"\vCreateStaff\x12&.smartfind.staff.v1.CreateStaffRequest\x1a\x19.smartfind.staff.v1.Staff\x12\\\n" +
	"\x0fCreateFoundItem\x12*.smartfind.staff.v1.CreateFoundItemRequest\x1a\x1d.smartfind.staff.v1.FoundItem\x12h\n" +
	"\x15UpdateFoundItemStatus\x120.smartfind.staff.v1.UpdateFoundItemStatusRequest\x1a\x1d.smartfind.staff.v1.FoundItem\x12g\n" +
	"\x0eListFoundItems\x12).smartfind.staff.v1.ListFoundItemsRequest\x1a*.smartfind.staff.v1.ListFoundItemsResponse\x12\x88\x01\n" +
	"\x19InitFoundItemImageUploads\x124.smartfind.staff.v1.InitFoundItemImageUploadsRequest\x1a5.smartfind.staff.v1.InitFoundItemImageUploadsResponse\x12k\n" +
	"\x1aDeleteFoundItemImageUpload\x125.smartfind.staff.v1.DeleteFoundItemImageUploadRequest\x1a\x16.google.protobuf.Empty\x12\xa0\x01\n" +
	"!SearchFoundItemMatchesByEmbedding\x12<.smartfind.staff.v1.SearchFoundItemMatchesByEmbeddingRequest\x1a=.smartfind.staff.v1.SearchFoundItemMatchesByEmbeddingResponse\x12[\n" +
	"\n" +
	"ListClaims\x12%.smartfind.staff.v1.ListClaimsRequest\x1a&.smartfind.staff.v1.ListClaimsResponse\x12T\n" +
	"\vReviewClaim\x12&.smartfind.staff.v1.ReviewClaimRequest\x1a\x1d.smartfind.staff.v1.ItemClaim\x12P\n" +
	"\vCreateRoute\x12&.smartfind.staff.v1.CreateRouteRequest\x1a\x19.smartfind.staff.v1.Route\x12M\n" +
	"\vDeleteRoute\x12&.smartfind.staff.v1.DeleteRouteRequest\x1a\x16.google.protobuf.Empty\x12[\n" +
	"\n" +
	"ListRoutes\x12%.smartfind.staff.v1.ListRoutesRequest\x1a&.smartfind.staff.v1.ListRoutesResponseB\x1dZ\x1bsmartfind/proto;smartfindpbb\x06proto3"

var (
	file_staff_proto_rawDescOnce sync.Once
	file_staff_proto_rawDescData []byte
)

func file_staff_proto_rawDescGZIP() []byte {
	file_staff_proto_rawDescOnce.Do(func() {
		file_staff_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_staff_proto_rawDesc), len(file_staff_proto_rawDesc)))
	})
	return file_staff_proto_rawDescData
}

var file_staff_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_staff_proto_goTypes = []any{
	(*Staff)(nil),                                     // 0: smartfind.staff.v1.Staff
	(*LoginRequest)(nil),                              // 1: smartfind.staff.v1.LoginRequest
	(*LoginResponse)(nil),                             // 2: smartfind.staff.v1.LoginResponse
	(*CreateStaffRequest)(nil),                        // 3: smartfind.staff.v1.CreateStaffRequest
	(*FoundItem)(nil),                                 // 4: smartfind.staff.v1.FoundItem
	(*CreateFoundItemRequest)(nil),                    // 5: smartfind.staff.v1.CreateFoundItemRequest
	(*InitFoundItemImageUploadsRequest)(nil),          // 6: smartfind.staff.v1.InitFoundItemImageUploadsRequest
	(*UploadFile)(nil),                                // 7: smartfind.staff.v1.UploadFile
	(*InitFoundItemImageUploadsResponse)(nil),         // 8: smartfind.staff.v1.InitFoundItemImageUploadsResponse
	(*UploadInit)(nil),                                // 9: smartfind.staff.v1.UploadInit
	(*DeleteFoundItemImageUploadRequest)(nil),         // 10: smartfind.staff.v1.DeleteFoundItemImageUploadRequest
	(*SearchFoundItemMatchesByEmbeddingRequest)(nil),  // 11: smartfind.staff.v1.SearchFoundItemMatchesByEmbeddingRequest
	(*SearchFoundItemMatchesByEmbeddingResponse)(nil), // 12: smartfind.staff.v1.SearchFoundItemMatchesByEmbeddingResponse
	(*FoundItemMatch)(nil),                            // 13: smartfind.staff.v1.FoundItemMatch
	(*UpdateFoundItemStatusRequest)(nil),              // 14: smartfind.staff.v1.UpdateFoundItemStatusRequest
	(*ListFoundItemsRequest)(nil),                     // 15: smartfind.staff.v1.ListFoundItemsRequest
	(*ListFoundItemsResponse)(nil),                    // 16: smartfind.staff.v1.ListFoundItemsResponse
	(*ItemClaim)(nil),                                 // 17: smartfind.staff.v1.ItemClaim
	(*ListClaimsRequest)(nil),                         // 18: smartfind.staff.v1.ListClaimsRequest
	(*ListClaimsResponse)(nil),                        // 19: smartfind.staff.v1.ListClaimsResponse
	(*ReviewClaimRequest)(nil),                        // 20: smartfind.staff.v1.ReviewClaimRequest
	(*Route)(nil),                                     // 21: smartfind.staff.v1.Route
	(*CreateRouteRequest)(nil),                        // 22: smartfind.staff.v1.CreateRouteRequest
	(*DeleteRouteRequest)(nil),                        // 23: smartfind.staff.v1.DeleteRouteRequest
	(*ListRoutesRequest)(nil),                         // 24: smartfind.staff.v1.ListRoutesRequest
	(*ListRoutesResponse)(nil),                        // 25: smartfind.staff.v1.ListRoutesResponse
	nil,                                               // 26: smartfind.staff.v1.UploadInit.HeadersEntry
	(*timestamppb.Timestamp)(nil),                     // 27: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                             // 28: google.protobuf.Empty
}
var file_staff_proto_depIdxs = []int32{
	27, // 0: smartfind.staff.v1.Staff.created_at:type_name -> google.protobuf.Timestamp
	27, // 1: smartfind.staff.v1.Staff.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: smartfind.staff.v1.LoginResponse.staff:type_name -> smartfind.staff.v1.Staff
	27, // 3: smartfind.staff.v1.FoundItem.date_found:type_name -> google.protobuf.Timestamp
	27, // 4: smartfind.staff.v1.FoundItem.created_at:type_name -> google.protobuf.Timestamp
	27, // 5: smartfind.staff.v1.FoundItem.updated_at:type_name -> google.protobuf.Timestamp
	27, // 6: smartfind.staff.v1.CreateFoundItemRequest.date_found:type_name -> google.protobuf.Timestamp
	7,  // 7: smartfind.staff.v1.InitFoundItemImageUploadsRequest.files:type_name -> smartfind.staff.v1.UploadFile
	9,  // 8: smartfind.staff.v1.InitFoundItemImageUploadsResponse.uploads:type_name -> smartfind.staff.v1.UploadInit
	26, // 9: smartfind.staff.v1.UploadInit.headers:type_name -> smartfind.staff.v1.UploadInit.HeadersEntry
	13, // 10: smartfind.staff.v1.SearchFoundItemMatchesByEmbeddingResponse.matches:type_name -> smartfind.staff.v1.FoundItemMatch
	4,  // 11: smartfind.staff.v1.FoundItemMatch.item:type_name -> smartfind.staff.v1.FoundItem
	4,  // 12: smartfind.staff.v1.ListFoundItemsResponse.items:type_name -> smartfind.staff.v1.FoundItem
	27, // 13: smartfind.staff.v1.ItemClaim.created_at:type_name -> google.protobuf.Timestamp
	27, // 14: smartfind.staff.v1.ItemClaim.updated_at:type_name -> google.protobuf.Timestamp
	17, // 15: smartfind.staff.v1.ListClaimsResponse.claims:type_name -> smartfind.staff.v1.ItemClaim
	27, // 16: smartfind.staff.v1.Route.created_at:type_name -> google.protobuf.Timestamp
	27, // 17: smartfind.staff.v1.Route.updated_at:type_name -> google.protobuf.Timestamp
	21, // 18: smartfind.staff.v1.ListRoutesResponse.routes:type_name -> smartfind.staff.v1.Route
	1,  // 19: smartfind.staff.v1.StaffService.Login:input_type -> smartfind.staff.v1.LoginRequest
	3,  // 20: smartfind.staff.v1.StaffService.CreateStaff:input_type -> smartfind.staff.v1.CreateStaffRequest
	5,  // 21: smartfind.staff.v1.StaffService.CreateFoundItem:input_type -> smartfind.staff.v1.CreateFoundItemRequest
	14, // 22: smartfind.staff.v1.StaffService.UpdateFoundItemStatus:input_type -> smartfind.staff.v1.UpdateFoundItemStatusRequest
	15, // 23: smartfind.staff.v1.StaffService.ListFoundItems:input_type -> smartfind.staff.v1.ListFoundItemsRequest
	6,  // 24: smartfind.staff.v1.StaffService.InitFoundItemImageUploads:input_type -> smartfind.staff.v1.InitFoundItemImageUploadsRequest
	10, // 25: smartfind.staff.v1.StaffService.DeleteFoundItemImageUpload:input_type -> smartfind.staff.v1.DeleteFoundItemImageUploadRequest
	11, // 26: smartfind.staff.v1.StaffService.SearchFoundItemMatchesByEmbedding:input_type -> smartfind.staff.v1.SearchFoundItemMatchesByEmbeddingRequest
	18, // 27: smartfind.staff.v1.StaffService.ListClaims:input_type -> smartfind.staff.v1.ListClaimsRequest
	20, // 28: smartfind.staff.v1.StaffService.ReviewClaim:input_type -> smartfind.staff.v1.ReviewClaimRequest
	22, // 29: smartfind.staff.v1.StaffService.CreateRoute:input_type -> smartfind.staff.v1.CreateRouteRequest
	23, // 30: smartfind.staff.v1.StaffService.DeleteRoute:input_type -> smartfind.staff.v1.DeleteRouteRequest
	24, // 31: smartfind.staff.v1.StaffService.ListRoutes:input_type -> smartfind.staff.v1.ListRoutesRequest
	2,  // 32: smartfind.staff.v1.StaffService.Login:output_type -> smartfind.staff.v1.LoginResponse
	0,  // 33: smartfind.staff.v1.StaffService.CreateStaff:output_type -> smartfind.staff.v1.Staff
	4,  // 34: smartfind.staff.v1.StaffService.CreateFoundItem:output_type -> smartfind.staff.v1.FoundItem
	4,  // 35: smartfind.staff.v1.StaffService.UpdateFoundItemStatus:output_type -> smartfind.staff.v1.FoundItem
	16, // 36: smartfind.staff.v1.StaffService.ListFoundItems:output_type -> smartfind.staff.v1.ListFoundItemsResponse
	8,  // 37: smartfind.staff.v1.StaffService.InitFoundItemImageUploads:output_type -> smartfind.staff.v1.InitFoundItemImageUploadsResponse
	28, // 38: smartfind.staff.v1.StaffService.DeleteFoundItemImageUpload:output_type -> google.protobuf.Empty
	12, // 39: smartfind.staff.v1.StaffService.SearchFoundItemMatchesByEmbedding:output_type -> smartfind.staff.v1.SearchFoundItemMatchesByEmbeddingResponse
	19, // 40: smartfind.staff.v1.StaffService.ListClaims:output_type -> smartfind.staff.v1.ListClaimsResponse
	17, // 41: smartfind.staff.v1.StaffService.ReviewClaim:output_type -> smartfind.staff.v1.ItemClaim
	21, // 42: smartfind.staff.v1.StaffService.CreateRoute:output_type -> smartfind.staff.v1.Route
	28, // 43: smartfind.staff.v1.StaffService.DeleteRoute:output_type -> google.protobuf.Empty
	25, // 44: smartfind.staff.v1.StaffService.ListRoutes:output_type -> smartfind.staff.v1.ListRoutesResponse
	32, // [32:45] is the sub-list for method output_type
	19, // [19:32] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_staff_proto_init() }
func file_staff_proto_init() {
	if File_staff_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_staff_proto_rawDesc), len(file_staff_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_staff_proto_goTypes,
		DependencyIndexes: file_staff_proto_depIdxs,
		MessageInfos:      file_staff_proto_msgTypes,
	}.Build()
	File_staff_proto = out.File
	file_staff_proto_goTypes = nil
	file_staff_proto_depIdxs = nil
}
