// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: staff.proto

package smartfindpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StaffService_Login_FullMethodName                             = "/smartfind.staff.v1.StaffService/Login"
	StaffService_CreateStaff_FullMethodName                       = "/smartfind.staff.v1.StaffService/CreateStaff"
	StaffService_CreateFoundItem_FullMethodName                   = "/smartfind.staff.v1.StaffService/CreateFoundItem"
	StaffService_UpdateFoundItemStatus_FullMethodName             = "/smartfind.staff.v1.StaffService/UpdateFoundItemStatus"
	StaffService_ListFoundItems_FullMethodName                    = "/smartfind.staff.v1.StaffService/ListFoundItems"
	StaffService_InitFoundItemImageUploads_FullMethodName         = "/smartfind.staff.v1.StaffService/InitFoundItemImageUploads"
	StaffService_DeleteFoundItemImageUpload_FullMethodName        = "/smartfind.staff.v1.StaffService/DeleteFoundItemImageUpload"
	StaffService_SearchFoundItemMatchesByEmbedding_FullMethodName = "/smartfind.staff.v1.StaffService/SearchFoundItemMatchesByEmbedding"
	StaffService_UpdateFoundItem_FullMethodName                   = "/smartfind.staff.v1.StaffService/UpdateFoundItem"
	StaffService_DeleteFoundItem_FullMethodName                   = "/smartfind.staff.v1.StaffService/DeleteFoundItem"
	StaffService_ListClaims_FullMethodName                        = "/smartfind.staff.v1.StaffService/ListClaims"
	StaffService_ReviewClaim_FullMethodName                       = "/smartfind.staff.v1.StaffService/ReviewClaim"
	StaffService_CreateRoute_FullMethodName                       = "/smartfind.staff.v1.StaffService/CreateRoute"
	StaffService_DeleteRoute_FullMethodName                       = "/smartfind.staff.v1.StaffService/DeleteRoute"
	StaffService_ListRoutes_FullMethodName                        = "/smartfind.staff.v1.StaffService/ListRoutes"
)

// StaffServiceClient is the client API for StaffService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StaffServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	CreateStaff(ctx context.Context, in *CreateStaffRequest, opts ...grpc.CallOption) (*Staff, error)
	CreateFoundItem(ctx context.Context, in *CreateFoundItemRequest, opts ...grpc.CallOption) (*FoundItem, error)
	UpdateFoundItemStatus(ctx context.Context, in *UpdateFoundItemStatusRequest, opts ...grpc.CallOption) (*FoundItem, error)
	ListFoundItems(ctx context.Context, in *ListFoundItemsRequest, opts ...grpc.CallOption) (*ListFoundItemsResponse, error)
	// Media: found-item image uploads (S3 presigned URLs + cleanup).
	InitFoundItemImageUploads(ctx context.Context, in *InitFoundItemImageUploadsRequest, opts ...grpc.CallOption) (*InitFoundItemImageUploadsResponse, error)
	DeleteFoundItemImageUpload(ctx context.Context, in *DeleteFoundItemImageUploadRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Internal-only: similarity search over found items using a query embedding.
	// Auth: requires x-internal-token; does NOT require x-forwarded-token.
	SearchFoundItemMatchesByEmbedding(ctx context.Context, in *SearchFoundItemMatchesByEmbeddingRequest, opts ...grpc.CallOption) (*SearchFoundItemMatchesByEmbeddingResponse, error)
	// Edits the free-form descriptive fields of a found item owned by the
	// calling staff member. Any of the twelve embedding slots that changed
	// causes the service to regenerate and upsert the item's embedding so
	// future similarity searches reflect the correction. Image keys may
	// also be replaced in the same call.
	UpdateFoundItem(ctx context.Context, in *UpdateFoundItemRequest, opts ...grpc.CallOption) (*FoundItem, error)
	// Hard-deletes a found item posted by the calling staff member.
	// Cascades to found_item_embeddings and rejects when any pending or
	// approved claim exists for the item.
	DeleteFoundItem(ctx context.Context, in *DeleteFoundItemRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListClaims(ctx context.Context, in *ListClaimsRequest, opts ...grpc.CallOption) (*ListClaimsResponse, error)
	ReviewClaim(ctx context.Context, in *ReviewClaimRequest, opts ...grpc.CallOption) (*ItemClaim, error)
	CreateRoute(ctx context.Context, in *CreateRouteRequest, opts ...grpc.CallOption) (*Route, error)
	DeleteRoute(ctx context.Context, in *DeleteRouteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListRoutes(ctx context.Context, in *ListRoutesRequest, opts ...grpc.CallOption) (*ListRoutesResponse, error)
}

type staffServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStaffServiceClient(cc grpc.ClientConnInterface) StaffServiceClient {
	return &staffServiceClient{cc}
}

func (c *staffServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, StaffService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffServiceClient) CreateStaff(ctx context.Context, in *CreateStaffRequest, opts ...grpc.CallOption) (*Staff, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Staff)
	err := c.cc.Invoke(ctx, StaffService_CreateStaff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffServiceClient) CreateFoundItem(ctx context.Context, in *CreateFoundItemRequest, opts ...grpc.CallOption) (*FoundItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FoundItem)
	err := c.cc.Invoke(ctx, StaffService_CreateFoundItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffServiceClient) UpdateFoundItemStatus(ctx context.Context, in *UpdateFoundItemStatusRequest, opts ...grpc.CallOption) (*FoundItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FoundItem)
	err := c.cc.Invoke(ctx, StaffService_UpdateFoundItemStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffServiceClient) ListFoundItems(ctx context.Context, in *ListFoundItemsRequest, opts ...grpc.CallOption) (*ListFoundItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFoundItemsResponse)
	err := c.cc.Invoke(ctx, StaffService_ListFoundItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffServiceClient) InitFoundItemImageUploads(ctx context.Context, in *InitFoundItemImageUploadsRequest, opts ...grpc.CallOption) (*InitFoundItemImageUploadsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitFoundItemImageUploadsResponse)
	err := c.cc.Invoke(ctx, StaffService_InitFoundItemImageUploads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffServiceClient) DeleteFoundItemImageUpload(ctx context.Context, in *DeleteFoundItemImageUploadRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StaffService_DeleteFoundItemImageUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffServiceClient) SearchFoundItemMatchesByEmbedding(ctx context.Context, in *SearchFoundItemMatchesByEmbeddingRequest, opts ...grpc.CallOption) (*SearchFoundItemMatchesByEmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchFoundItemMatchesByEmbeddingResponse)
	err := c.cc.Invoke(ctx, StaffService_SearchFoundItemMatchesByEmbedding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffServiceClient) UpdateFoundItem(ctx context.Context, in *UpdateFoundItemRequest, opts ...grpc.CallOption) (*FoundItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FoundItem)
	err := c.cc.Invoke(ctx, StaffService_UpdateFoundItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffServiceClient) DeleteFoundItem(ctx context.Context, in *DeleteFoundItemRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StaffService_DeleteFoundItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffServiceClient) ListClaims(ctx context.Context, in *ListClaimsRequest, opts ...grpc.CallOption) (*ListClaimsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListClaimsResponse)
	err := c.cc.Invoke(ctx, StaffService_ListClaims_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffServiceClient) ReviewClaim(ctx context.Context, in *ReviewClaimRequest, opts ...grpc.CallOption) (*ItemClaim, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemClaim)
	err := c.cc.Invoke(ctx, StaffService_ReviewClaim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffServiceClient) CreateRoute(ctx context.Context, in *CreateRouteRequest, opts ...grpc.CallOption) (*Route, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Route)
	err := c.cc.Invoke(ctx, StaffService_CreateRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffServiceClient) DeleteRoute(ctx context.Context, in *DeleteRouteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StaffService_DeleteRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffServiceClient) ListRoutes(ctx context.Context, in *ListRoutesRequest, opts ...grpc.CallOption) (*ListRoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoutesResponse)
	err := c.cc.Invoke(ctx, StaffService_ListRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StaffServiceServer is the server API for StaffService service.
// All implementations must embed UnimplementedStaffServiceServer
// for forward compatibility.
type StaffServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	CreateStaff(context.Context, *CreateStaffRequest) (*Staff, error)
	CreateFoundItem(context.Context, *CreateFoundItemRequest) (*FoundItem, error)
	UpdateFoundItemStatus(context.Context, *UpdateFoundItemStatusRequest) (*FoundItem, error)
	ListFoundItems(context.Context, *ListFoundItemsRequest) (*ListFoundItemsResponse, error)
	// Media: found-item image uploads (S3 presigned URLs + cleanup).
	InitFoundItemImageUploads(context.Context, *InitFoundItemImageUploadsRequest) (*InitFoundItemImageUploadsResponse, error)
	DeleteFoundItemImageUpload(context.Context, *DeleteFoundItemImageUploadRequest) (*emptypb.Empty, error)
	// Internal-only: similarity search over found items using a query embedding.
	// Auth: requires x-internal-token; does NOT require x-forwarded-token.
	SearchFoundItemMatchesByEmbedding(context.Context, *SearchFoundItemMatchesByEmbeddingRequest) (*SearchFoundItemMatchesByEmbeddingResponse, error)
	// Edits the free-form descriptive fields of a found item owned by the
	// calling staff member. Any of the twelve embedding slots that changed
	// causes the service to regenerate and upsert the item's embedding so
	// future similarity searches reflect the correction. Image keys may
	// also be replaced in the same call.
	UpdateFoundItem(context.Context, *UpdateFoundItemRequest) (*FoundItem, error)
	// Hard-deletes a found item posted by the calling staff member.
	// Cascades to found_item_embeddings and rejects when any pending or
	// approved claim exists for the item.
	DeleteFoundItem(context.Context, *DeleteFoundItemRequest) (*emptypb.Empty, error)
	ListClaims(context.Context, *ListClaimsRequest) (*ListClaimsResponse, error)
	ReviewClaim(context.Context, *ReviewClaimRequest) (*ItemClaim, error)
	CreateRoute(context.Context, *CreateRouteRequest) (*Route, error)
	DeleteRoute(context.Context, *DeleteRouteRequest) (*emptypb.Empty, error)
	ListRoutes(context.Context, *ListRoutesRequest) (*ListRoutesResponse, error)
	mustEmbedUnimplementedStaffServiceServer()
}

// UnimplementedStaffServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStaffServiceServer struct{}

func (UnimplementedStaffServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedStaffServiceServer) CreateStaff(context.Context, *CreateStaffRequest) (*Staff, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateStaff not implemented")
}
func (UnimplementedStaffServiceServer) CreateFoundItem(context.Context, *CreateFoundItemRequest) (*FoundItem, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFoundItem not implemented")
}
func (UnimplementedStaffServiceServer) UpdateFoundItemStatus(context.Context, *UpdateFoundItemStatusRequest) (*FoundItem, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFoundItemStatus not implemented")
}
func (UnimplementedStaffServiceServer) ListFoundItems(context.Context, *ListFoundItemsRequest) (*ListFoundItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFoundItems not implemented")
}
func (UnimplementedStaffServiceServer) InitFoundItemImageUploads(context.Context, *InitFoundItemImageUploadsRequest) (*InitFoundItemImageUploadsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitFoundItemImageUploads not implemented")
}
func (UnimplementedStaffServiceServer) DeleteFoundItemImageUpload(context.Context, *DeleteFoundItemImageUploadRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFoundItemImageUpload not implemented")
}
func (UnimplementedStaffServiceServer) SearchFoundItemMatchesByEmbedding(context.Context, *SearchFoundItemMatchesByEmbeddingRequest) (*SearchFoundItemMatchesByEmbeddingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchFoundItemMatchesByEmbedding not implemented")
}
func (UnimplementedStaffServiceServer) UpdateFoundItem(context.Context, *UpdateFoundItemRequest) (*FoundItem, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFoundItem not implemented")
}
func (UnimplementedStaffServiceServer) DeleteFoundItem(context.Context, *DeleteFoundItemRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFoundItem not implemented")
}
func (UnimplementedStaffServiceServer) ListClaims(context.Context, *ListClaimsRequest) (*ListClaimsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListClaims not implemented")
}
func (UnimplementedStaffServiceServer) ReviewClaim(context.Context, *ReviewClaimRequest) (*ItemClaim, error) {
	return nil, status.Error(codes.Unimplemented, "method ReviewClaim not implemented")
}
func (UnimplementedStaffServiceServer) CreateRoute(context.Context, *CreateRouteRequest) (*Route, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRoute not implemented")
}
func (UnimplementedStaffServiceServer) DeleteRoute(context.Context, *DeleteRouteRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRoute not implemented")
}
func (UnimplementedStaffServiceServer) ListRoutes(context.Context, *ListRoutesRequest) (*ListRoutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRoutes not implemented")
}
func (UnimplementedStaffServiceServer) mustEmbedUnimplementedStaffServiceServer() {}
func (UnimplementedStaffServiceServer) testEmbeddedByValue()                      {}

// UnsafeStaffServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StaffServiceServer will
// result in compilation errors.
type UnsafeStaffServiceServer interface {
	mustEmbedUnimplementedStaffServiceServer()
}

func RegisterStaffServiceServer(s grpc.ServiceRegistrar, srv StaffServiceServer) {
	// If the following call panics, it indicates UnimplementedStaffServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StaffService_ServiceDesc, srv)
}

func _StaffService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffService_CreateStaff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStaffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServiceServer).CreateStaff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffService_CreateStaff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServiceServer).CreateStaff(ctx, req.(*CreateStaffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffService_CreateFoundItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFoundItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServiceServer).CreateFoundItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffService_CreateFoundItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServiceServer).CreateFoundItem(ctx, req.(*CreateFoundItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffService_UpdateFoundItemStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFoundItemStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServiceServer).UpdateFoundItemStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffService_UpdateFoundItemStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServiceServer).UpdateFoundItemStatus(ctx, req.(*UpdateFoundItemStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffService_ListFoundItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFoundItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServiceServer).ListFoundItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffService_ListFoundItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServiceServer).ListFoundItems(ctx, req.(*ListFoundItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffService_InitFoundItemImageUploads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitFoundItemImageUploadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServiceServer).InitFoundItemImageUploads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffService_InitFoundItemImageUploads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServiceServer).InitFoundItemImageUploads(ctx, req.(*InitFoundItemImageUploadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffService_DeleteFoundItemImageUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFoundItemImageUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServiceServer).DeleteFoundItemImageUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffService_DeleteFoundItemImageUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServiceServer).DeleteFoundItemImageUpload(ctx, req.(*DeleteFoundItemImageUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffService_SearchFoundItemMatchesByEmbedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchFoundItemMatchesByEmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServiceServer).SearchFoundItemMatchesByEmbedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffService_SearchFoundItemMatchesByEmbedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServiceServer).SearchFoundItemMatchesByEmbedding(ctx, req.(*SearchFoundItemMatchesByEmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffService_UpdateFoundItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFoundItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServiceServer).UpdateFoundItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffService_UpdateFoundItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServiceServer).UpdateFoundItem(ctx, req.(*UpdateFoundItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffService_DeleteFoundItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFoundItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServiceServer).DeleteFoundItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffService_DeleteFoundItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServiceServer).DeleteFoundItem(ctx, req.(*DeleteFoundItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffService_ListClaims_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClaimsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServiceServer).ListClaims(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffService_ListClaims_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServiceServer).ListClaims(ctx, req.(*ListClaimsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffService_ReviewClaim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewClaimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServiceServer).ReviewClaim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffService_ReviewClaim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServiceServer).ReviewClaim(ctx, req.(*ReviewClaimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffService_CreateRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServiceServer).CreateRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffService_CreateRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServiceServer).CreateRoute(ctx, req.(*CreateRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffService_DeleteRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServiceServer).DeleteRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffService_DeleteRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServiceServer).DeleteRoute(ctx, req.(*DeleteRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffService_ListRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServiceServer).ListRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffService_ListRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServiceServer).ListRoutes(ctx, req.(*ListRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StaffService_ServiceDesc is the grpc.ServiceDesc for StaffService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StaffService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smartfind.staff.v1.StaffService",
	HandlerType: (*StaffServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _StaffService_Login_Handler,
		},
		{
			MethodName: "CreateStaff",
			Handler:    _StaffService_CreateStaff_Handler,
		},
		{
			MethodName: "CreateFoundItem",
			Handler:    _StaffService_CreateFoundItem_Handler,
		},
		{
			MethodName: "UpdateFoundItemStatus",
			Handler:    _StaffService_UpdateFoundItemStatus_Handler,
		},
		{
			MethodName: "ListFoundItems",
			Handler:    _StaffService_ListFoundItems_Handler,
		},
		{
			MethodName: "InitFoundItemImageUploads",
			Handler:    _StaffService_InitFoundItemImageUploads_Handler,
		},
		{
			MethodName: "DeleteFoundItemImageUpload",
			Handler:    _StaffService_DeleteFoundItemImageUpload_Handler,
		},
		{
			MethodName: "SearchFoundItemMatchesByEmbedding",
			Handler:    _StaffService_SearchFoundItemMatchesByEmbedding_Handler,
		},
		{
			MethodName: "UpdateFoundItem",
			Handler:    _StaffService_UpdateFoundItem_Handler,
		},
		{
			MethodName: "DeleteFoundItem",
			Handler:    _StaffService_DeleteFoundItem_Handler,
		},
		{
			MethodName: "ListClaims",
			Handler:    _StaffService_ListClaims_Handler,
		},
		{
			MethodName: "ReviewClaim",
			Handler:    _StaffService_ReviewClaim_Handler,
		},
		{
			MethodName: "CreateRoute",
			Handler:    _StaffService_CreateRoute_Handler,
		},
		{
			MethodName: "DeleteRoute",
			Handler:    _StaffService_DeleteRoute_Handler,
		},
		{
			MethodName: "ListRoutes",
			Handler:    _StaffService_ListRoutes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "staff.proto",
}
