// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: passenger.proto

package smartfindpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PassengerService_Login_FullMethodName                  = "/smartfind.passenger.v1.PassengerService/Login"
	PassengerService_CreateLostReport_FullMethodName       = "/smartfind.passenger.v1.PassengerService/CreateLostReport"
	PassengerService_UpdateLostReport_FullMethodName       = "/smartfind.passenger.v1.PassengerService/UpdateLostReport"
	PassengerService_ListLostReports_FullMethodName        = "/smartfind.passenger.v1.PassengerService/ListLostReports"
	PassengerService_DeleteLostReport_FullMethodName       = "/smartfind.passenger.v1.PassengerService/DeleteLostReport"
	PassengerService_SearchFoundItemMatches_FullMethodName = "/smartfind.passenger.v1.PassengerService/SearchFoundItemMatches"
	PassengerService_FileClaim_FullMethodName              = "/smartfind.passenger.v1.PassengerService/FileClaim"
	PassengerService_ListMyClaims_FullMethodName           = "/smartfind.passenger.v1.PassengerService/ListMyClaims"
	PassengerService_ListNotifications_FullMethodName      = "/smartfind.passenger.v1.PassengerService/ListNotifications"
	PassengerService_MarkNotificationRead_FullMethodName   = "/smartfind.passenger.v1.PassengerService/MarkNotificationRead"
)

// PassengerServiceClient is the client API for PassengerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PassengerServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	CreateLostReport(ctx context.Context, in *CreateLostReportRequest, opts ...grpc.CallOption) (*LostReport, error)
	UpdateLostReport(ctx context.Context, in *UpdateLostReportRequest, opts ...grpc.CallOption) (*LostReport, error)
	ListLostReports(ctx context.Context, in *ListLostReportsRequest, opts ...grpc.CallOption) (*ListLostReportsResponse, error)
	DeleteLostReport(ctx context.Context, in *DeleteLostReportRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SearchFoundItemMatches(ctx context.Context, in *SearchFoundItemMatchesRequest, opts ...grpc.CallOption) (*SearchFoundItemMatchesResponse, error)
	FileClaim(ctx context.Context, in *FileClaimRequest, opts ...grpc.CallOption) (*ItemClaim, error)
	ListMyClaims(ctx context.Context, in *ListMyClaimsRequest, opts ...grpc.CallOption) (*ListMyClaimsResponse, error)
	ListNotifications(ctx context.Context, in *ListNotificationsRequest, opts ...grpc.CallOption) (*ListNotificationsResponse, error)
	MarkNotificationRead(ctx context.Context, in *MarkNotificationReadRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type passengerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPassengerServiceClient(cc grpc.ClientConnInterface) PassengerServiceClient {
	return &passengerServiceClient{cc}
}

func (c *passengerServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, PassengerService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerServiceClient) CreateLostReport(ctx context.Context, in *CreateLostReportRequest, opts ...grpc.CallOption) (*LostReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LostReport)
	err := c.cc.Invoke(ctx, PassengerService_CreateLostReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerServiceClient) UpdateLostReport(ctx context.Context, in *UpdateLostReportRequest, opts ...grpc.CallOption) (*LostReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LostReport)
	err := c.cc.Invoke(ctx, PassengerService_UpdateLostReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerServiceClient) ListLostReports(ctx context.Context, in *ListLostReportsRequest, opts ...grpc.CallOption) (*ListLostReportsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLostReportsResponse)
	err := c.cc.Invoke(ctx, PassengerService_ListLostReports_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerServiceClient) DeleteLostReport(ctx context.Context, in *DeleteLostReportRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PassengerService_DeleteLostReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerServiceClient) SearchFoundItemMatches(ctx context.Context, in *SearchFoundItemMatchesRequest, opts ...grpc.CallOption) (*SearchFoundItemMatchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchFoundItemMatchesResponse)
	err := c.cc.Invoke(ctx, PassengerService_SearchFoundItemMatches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerServiceClient) FileClaim(ctx context.Context, in *FileClaimRequest, opts ...grpc.CallOption) (*ItemClaim, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemClaim)
	err := c.cc.Invoke(ctx, PassengerService_FileClaim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerServiceClient) ListMyClaims(ctx context.Context, in *ListMyClaimsRequest, opts ...grpc.CallOption) (*ListMyClaimsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyClaimsResponse)
	err := c.cc.Invoke(ctx, PassengerService_ListMyClaims_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerServiceClient) ListNotifications(ctx context.Context, in *ListNotificationsRequest, opts ...grpc.CallOption) (*ListNotificationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNotificationsResponse)
	err := c.cc.Invoke(ctx, PassengerService_ListNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerServiceClient) MarkNotificationRead(ctx context.Context, in *MarkNotificationReadRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PassengerService_MarkNotificationRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PassengerServiceServer is the server API for PassengerService service.
// All implementations must embed UnimplementedPassengerServiceServer
// for forward compatibility.
type PassengerServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	CreateLostReport(context.Context, *CreateLostReportRequest) (*LostReport, error)
	UpdateLostReport(context.Context, *UpdateLostReportRequest) (*LostReport, error)
	ListLostReports(context.Context, *ListLostReportsRequest) (*ListLostReportsResponse, error)
	DeleteLostReport(context.Context, *DeleteLostReportRequest) (*emptypb.Empty, error)
	SearchFoundItemMatches(context.Context, *SearchFoundItemMatchesRequest) (*SearchFoundItemMatchesResponse, error)
	FileClaim(context.Context, *FileClaimRequest) (*ItemClaim, error)
	ListMyClaims(context.Context, *ListMyClaimsRequest) (*ListMyClaimsResponse, error)
	ListNotifications(context.Context, *ListNotificationsRequest) (*ListNotificationsResponse, error)
	MarkNotificationRead(context.Context, *MarkNotificationReadRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedPassengerServiceServer()
}

// UnimplementedPassengerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPassengerServiceServer struct{}

func (UnimplementedPassengerServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedPassengerServiceServer) CreateLostReport(context.Context, *CreateLostReportRequest) (*LostReport, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLostReport not implemented")
}
func (UnimplementedPassengerServiceServer) UpdateLostReport(context.Context, *UpdateLostReportRequest) (*LostReport, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLostReport not implemented")
}
func (UnimplementedPassengerServiceServer) ListLostReports(context.Context, *ListLostReportsRequest) (*ListLostReportsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLostReports not implemented")
}
func (UnimplementedPassengerServiceServer) DeleteLostReport(context.Context, *DeleteLostReportRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLostReport not implemented")
}
func (UnimplementedPassengerServiceServer) SearchFoundItemMatches(context.Context, *SearchFoundItemMatchesRequest) (*SearchFoundItemMatchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchFoundItemMatches not implemented")
}
func (UnimplementedPassengerServiceServer) FileClaim(context.Context, *FileClaimRequest) (*ItemClaim, error) {
	return nil, status.Error(codes.Unimplemented, "method FileClaim not implemented")
}
func (UnimplementedPassengerServiceServer) ListMyClaims(context.Context, *ListMyClaimsRequest) (*ListMyClaimsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyClaims not implemented")
}
func (UnimplementedPassengerServiceServer) ListNotifications(context.Context, *ListNotificationsRequest) (*ListNotificationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNotifications not implemented")
}
func (UnimplementedPassengerServiceServer) MarkNotificationRead(context.Context, *MarkNotificationReadRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkNotificationRead not implemented")
}
func (UnimplementedPassengerServiceServer) mustEmbedUnimplementedPassengerServiceServer() {}
func (UnimplementedPassengerServiceServer) testEmbeddedByValue()                          {}

// UnsafePassengerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PassengerServiceServer will
// result in compilation errors.
type UnsafePassengerServiceServer interface {
	mustEmbedUnimplementedPassengerServiceServer()
}

func RegisterPassengerServiceServer(s grpc.ServiceRegistrar, srv PassengerServiceServer) {
	// If the following call panics, it indicates UnimplementedPassengerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PassengerService_ServiceDesc, srv)
}

func _PassengerService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassengerService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerService_CreateLostReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLostReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerServiceServer).CreateLostReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassengerService_CreateLostReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerServiceServer).CreateLostReport(ctx, req.(*CreateLostReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerService_UpdateLostReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLostReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerServiceServer).UpdateLostReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassengerService_UpdateLostReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerServiceServer).UpdateLostReport(ctx, req.(*UpdateLostReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerService_ListLostReports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLostReportsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerServiceServer).ListLostReports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassengerService_ListLostReports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerServiceServer).ListLostReports(ctx, req.(*ListLostReportsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerService_DeleteLostReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLostReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerServiceServer).DeleteLostReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassengerService_DeleteLostReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerServiceServer).DeleteLostReport(ctx, req.(*DeleteLostReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerService_SearchFoundItemMatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchFoundItemMatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerServiceServer).SearchFoundItemMatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassengerService_SearchFoundItemMatches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerServiceServer).SearchFoundItemMatches(ctx, req.(*SearchFoundItemMatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerService_FileClaim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileClaimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerServiceServer).FileClaim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassengerService_FileClaim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerServiceServer).FileClaim(ctx, req.(*FileClaimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerService_ListMyClaims_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyClaimsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerServiceServer).ListMyClaims(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassengerService_ListMyClaims_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerServiceServer).ListMyClaims(ctx, req.(*ListMyClaimsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerService_ListNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerServiceServer).ListNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassengerService_ListNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerServiceServer).ListNotifications(ctx, req.(*ListNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerService_MarkNotificationRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkNotificationReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerServiceServer).MarkNotificationRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassengerService_MarkNotificationRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerServiceServer).MarkNotificationRead(ctx, req.(*MarkNotificationReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PassengerService_ServiceDesc is the grpc.ServiceDesc for PassengerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PassengerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smartfind.passenger.v1.PassengerService",
	HandlerType: (*PassengerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _PassengerService_Login_Handler,
		},
		{
			MethodName: "CreateLostReport",
			Handler:    _PassengerService_CreateLostReport_Handler,
		},
		{
			MethodName: "UpdateLostReport",
			Handler:    _PassengerService_UpdateLostReport_Handler,
		},
		{
			MethodName: "ListLostReports",
			Handler:    _PassengerService_ListLostReports_Handler,
		},
		{
			MethodName: "DeleteLostReport",
			Handler:    _PassengerService_DeleteLostReport_Handler,
		},
		{
			MethodName: "SearchFoundItemMatches",
			Handler:    _PassengerService_SearchFoundItemMatches_Handler,
		},
		{
			MethodName: "FileClaim",
			Handler:    _PassengerService_FileClaim_Handler,
		},
		{
			MethodName: "ListMyClaims",
			Handler:    _PassengerService_ListMyClaims_Handler,
		},
		{
			MethodName: "ListNotifications",
			Handler:    _PassengerService_ListNotifications_Handler,
		},
		{
			MethodName: "MarkNotificationRead",
			Handler:    _PassengerService_MarkNotificationRead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "passenger.proto",
}
