// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: passenger.proto

package smartfindpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Passenger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,7,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Passenger) Reset() {
	*x = Passenger{}
	mi := &file_passenger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Passenger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Passenger) ProtoMessage() {}

func (x *Passenger) ProtoReflect() protoreflect.Message {
	mi := &file_passenger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Passenger.ProtoReflect.Descriptor instead.
func (*Passenger) Descriptor() ([]byte, []int) {
	return file_passenger_proto_rawDescGZIP(), []int{0}
}

func (x *Passenger) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Passenger) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Passenger) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Passenger) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Passenger) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Passenger) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Passenger) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdToken       string                 `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_passenger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_passenger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_passenger_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passenger     *Passenger             `protobuf:"bytes,1,opt,name=passenger,proto3" json:"passenger,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_passenger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_passenger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_passenger_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResponse) GetPassenger() *Passenger {
	if x != nil {
		return x.Passenger
	}
	return nil
}

func (x *LoginResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type LostReport struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReporterPassengerId string                 `protobuf:"bytes,2,opt,name=reporter_passenger_id,json=reporterPassengerId,proto3" json:"reporter_passenger_id,omitempty"`
	ItemName            string                 `protobuf:"bytes,3,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	ItemDescription     string                 `protobuf:"bytes,4,opt,name=item_description,json=itemDescription,proto3" json:"item_description,omitempty"`
	ItemType            string                 `protobuf:"bytes,5,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	Brand               string                 `protobuf:"bytes,6,opt,name=brand,proto3" json:"brand,omitempty"`
	Model               string                 `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`
	Color               string                 `protobuf:"bytes,8,opt,name=color,proto3" json:"color,omitempty"`
	Material            string                 `protobuf:"bytes,9,opt,name=material,proto3" json:"material,omitempty"`
	ItemCondition       string                 `protobuf:"bytes,10,opt,name=item_condition,json=itemCondition,proto3" json:"item_condition,omitempty"`
	Category            string                 `protobuf:"bytes,11,opt,name=category,proto3" json:"category,omitempty"`
	LocationLost        string                 `protobuf:"bytes,12,opt,name=location_lost,json=locationLost,proto3" json:"location_lost,omitempty"`
	RouteOrStation      string                 `protobuf:"bytes,13,opt,name=route_or_station,json=routeOrStation,proto3" json:"route_or_station,omitempty"`
	RouteId             string                 `protobuf:"bytes,14,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	DateLost            *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_lost,json=dateLost,proto3" json:"date_lost,omitempty"`
	Status              string                 `protobuf:"bytes,16,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LostReport) Reset() {
	*x = LostReport{}
	mi := &file_passenger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LostReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LostReport) ProtoMessage() {}

func (x *LostReport) ProtoReflect() protoreflect.Message {
	mi := &file_passenger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LostReport.ProtoReflect.Descriptor instead.
func (*LostReport) Descriptor() ([]byte, []int) {
	return file_passenger_proto_rawDescGZIP(), []int{3}
}

func (x *LostReport) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LostReport) GetReporterPassengerId() string {
	if x != nil {
		return x.ReporterPassengerId
	}
	return ""
}

func (x *LostReport) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *LostReport) GetItemDescription() string {
	if x != nil {
		return x.ItemDescription
	}
	return ""
}

func (x *LostReport) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *LostReport) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *LostReport) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LostReport) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *LostReport) GetMaterial() string {
	if x != nil {
		return x.Material
	}
	return ""
}

func (x *LostReport) GetItemCondition() string {
	if x != nil {
		return x.ItemCondition
	}
	return ""
}

func (x *LostReport) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *LostReport) GetLocationLost() string {
	if x != nil {
		return x.LocationLost
	}
	return ""
}

func (x *LostReport) GetRouteOrStation() string {
	if x != nil {
		return x.RouteOrStation
	}
	return ""
}

func (x *LostReport) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *LostReport) GetDateLost() *timestamppb.Timestamp {
	if x != nil {
		return x.DateLost
	}
	return nil
}

func (x *LostReport) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LostReport) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *LostReport) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateLostReportRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PassengerId     string                 `protobuf:"bytes,1,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	ItemName        string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	ItemDescription string                 `protobuf:"bytes,3,opt,name=item_description,json=itemDescription,proto3" json:"item_description,omitempty"`
	ItemType        string                 `protobuf:"bytes,4,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	Brand           string                 `protobuf:"bytes,5,opt,name=brand,proto3" json:"brand,omitempty"`
	Model           string                 `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	Color           string                 `protobuf:"bytes,7,opt,name=color,proto3" json:"color,omitempty"`
	Material        string                 `protobuf:"bytes,8,opt,name=material,proto3" json:"material,omitempty"`
	ItemCondition   string                 `protobuf:"bytes,9,opt,name=item_condition,json=itemCondition,proto3" json:"item_condition,omitempty"`
	Category        string                 `protobuf:"bytes,10,opt,name=category,proto3" json:"category,omitempty"`
	LocationLost    string                 `protobuf:"bytes,11,opt,name=location_lost,json=locationLost,proto3" json:"location_lost,omitempty"`
	RouteOrStation  string                 `protobuf:"bytes,12,opt,name=route_or_station,json=routeOrStation,proto3" json:"route_or_station,omitempty"`
	RouteId         string                 `protobuf:"bytes,13,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	DateLost        *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=date_lost,json=dateLost,proto3" json:"date_lost,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateLostReportRequest) Reset() {
	*x = CreateLostReportRequest{}
	mi := &file_passenger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLostReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLostReportRequest) ProtoMessage() {}

func (x *CreateLostReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_passenger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLostReportRequest.ProtoReflect.Descriptor instead.
func (*CreateLostReportRequest) Descriptor() ([]byte, []int) {
	return file_passenger_proto_rawDescGZIP(), []int{4}
}

func (x *CreateLostReportRequest) GetPassengerId() string {
	if x != nil {
		return x.PassengerId
	}
	return ""
}

func (x *CreateLostReportRequest) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *CreateLostReportRequest) GetItemDescription() string {
	if x != nil {
		return x.ItemDescription
	}
	return ""
}

func (x *CreateLostReportRequest) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *CreateLostReportRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CreateLostReportRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateLostReportRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *CreateLostReportRequest) GetMaterial() string {
	if x != nil {
		return x.Material
	}
	return ""
}

func (x *CreateLostReportRequest) GetItemCondition() string {
	if x != nil {
		return x.ItemCondition
	}
	return ""
}

func (x *CreateLostReportRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateLostReportRequest) GetLocationLost() string {
	if x != nil {
		return x.LocationLost
	}
	return ""
}

func (x *CreateLostReportRequest) GetRouteOrStation() string {
	if x != nil {
		return x.RouteOrStation
	}
	return ""
}

func (x *CreateLostReportRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *CreateLostReportRequest) GetDateLost() *timestamppb.Timestamp {
	if x != nil {
		return x.DateLost
	}
	return nil
}

// UpdateLostReportRequest patches any subset of the free-form fields on a
// lost report owned by `passenger_id`. Fields left as the proto default
// (empty string / zero timestamp) are ignored — clients wanting to clear a
// field should send a single space or update an adjacent field. When any of
// the twelve slots that feed the match embedding change, the passenger
// service re-computes the embedding and upserts it.
type UpdateLostReportRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PassengerId     string                 `protobuf:"bytes,1,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	LostReportId    string                 `protobuf:"bytes,2,opt,name=lost_report_id,json=lostReportId,proto3" json:"lost_report_id,omitempty"`
	ItemName        string                 `protobuf:"bytes,3,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	ItemDescription string                 `protobuf:"bytes,4,opt,name=item_description,json=itemDescription,proto3" json:"item_description,omitempty"`
	ItemType        string                 `protobuf:"bytes,5,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	Brand           string                 `protobuf:"bytes,6,opt,name=brand,proto3" json:"brand,omitempty"`
	Model           string                 `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`
	Color           string                 `protobuf:"bytes,8,opt,name=color,proto3" json:"color,omitempty"`
	Material        string                 `protobuf:"bytes,9,opt,name=material,proto3" json:"material,omitempty"`
	ItemCondition   string                 `protobuf:"bytes,10,opt,name=item_condition,json=itemCondition,proto3" json:"item_condition,omitempty"`
	Category        string                 `protobuf:"bytes,11,opt,name=category,proto3" json:"category,omitempty"`
	LocationLost    string                 `protobuf:"bytes,12,opt,name=location_lost,json=locationLost,proto3" json:"location_lost,omitempty"`
	RouteOrStation  string                 `protobuf:"bytes,13,opt,name=route_or_station,json=routeOrStation,proto3" json:"route_or_station,omitempty"`
	RouteId         string                 `protobuf:"bytes,14,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	DateLost        *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_lost,json=dateLost,proto3" json:"date_lost,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateLostReportRequest) Reset() {
	*x = UpdateLostReportRequest{}
	mi := &file_passenger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLostReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLostReportRequest) ProtoMessage() {}

func (x *UpdateLostReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_passenger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLostReportRequest.ProtoReflect.Descriptor instead.
func (*UpdateLostReportRequest) Descriptor() ([]byte, []int) {
	return file_passenger_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateLostReportRequest) GetPassengerId() string {
	if x != nil {
		return x.PassengerId
	}
	return ""
}

func (x *UpdateLostReportRequest) GetLostReportId() string {
	if x != nil {
		return x.LostReportId
	}
	return ""
}

func (x *UpdateLostReportRequest) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *UpdateLostReportRequest) GetItemDescription() string {
	if x != nil {
		return x.ItemDescription
	}
	return ""
}

func (x *UpdateLostReportRequest) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *UpdateLostReportRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *UpdateLostReportRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UpdateLostReportRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *UpdateLostReportRequest) GetMaterial() string {
	if x != nil {
		return x.Material
	}
	return ""
}

func (x *UpdateLostReportRequest) GetItemCondition() string {
	if x != nil {
		return x.ItemCondition
	}
	return ""
}

func (x *UpdateLostReportRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateLostReportRequest) GetLocationLost() string {
	if x != nil {
		return x.LocationLost
	}
	return ""
}

func (x *UpdateLostReportRequest) GetRouteOrStation() string {
	if x != nil {
		return x.RouteOrStation
	}
	return ""
}

func (x *UpdateLostReportRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *UpdateLostReportRequest) GetDateLost() *timestamppb.Timestamp {
	if x != nil {
		return x.DateLost
	}
	return nil
}

type ListLostReportsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PassengerId   string                 `protobuf:"bytes,1,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLostReportsRequest) Reset() {
	*x = ListLostReportsRequest{}
	mi := &file_passenger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLostReportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLostReportsRequest) ProtoMessage() {}

func (x *ListLostReportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_passenger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLostReportsRequest.ProtoReflect.Descriptor instead.
func (*ListLostReportsRequest) Descriptor() ([]byte, []int) {
	return file_passenger_proto_rawDescGZIP(), []int{6}
}

func (x *ListLostReportsRequest) GetPassengerId() string {
	if x != nil {
		return x.PassengerId
	}
	return ""
}

func (x *ListLostReportsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListLostReportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*LostReport          `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLostReportsResponse) Reset() {
	*x = ListLostReportsResponse{}
	mi := &file_passenger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLostReportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLostReportsResponse) ProtoMessage() {}

func (x *ListLostReportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_passenger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLostReportsResponse.ProtoReflect.Descriptor instead.
func (*ListLostReportsResponse) Descriptor() ([]byte, []int) {
	return file_passenger_proto_rawDescGZIP(), []int{7}
}

func (x *ListLostReportsResponse) GetReports() []*LostReport {
	if x != nil {
		return x.Reports
	}
	return nil
}

type DeleteLostReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PassengerId   string                 `protobuf:"bytes,1,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	LostReportId  string                 `protobuf:"bytes,2,opt,name=lost_report_id,json=lostReportId,proto3" json:"lost_report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLostReportRequest) Reset() {
	*x = DeleteLostReportRequest{}
	mi := &file_passenger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLostReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLostReportRequest) ProtoMessage() {}

func (x *DeleteLostReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_passenger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLostReportRequest.ProtoReflect.Descriptor instead.
func (*DeleteLostReportRequest) Descriptor() ([]byte, []int) {
	return file_passenger_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteLostReportRequest) GetPassengerId() string {
	if x != nil {
		return x.PassengerId
	}
	return ""
}

func (x *DeleteLostReportRequest) GetLostReportId() string {
	if x != nil {
		return x.LostReportId
	}
	return ""
}

type FoundItemMatch struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FoundItemId     string                 `protobuf:"bytes,1,opt,name=found_item_id,json=foundItemId,proto3" json:"found_item_id,omitempty"`
	ItemName        string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	ItemDescription string                 `protobuf:"bytes,3,opt,name=item_description,json=itemDescription,proto3" json:"item_description,omitempty"`
	ItemType        string                 `protobuf:"bytes,4,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	Brand           string                 `protobuf:"bytes,5,opt,name=brand,proto3" json:"brand,omitempty"`
	Model           string                 `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	Color           string                 `protobuf:"bytes,7,opt,name=color,proto3" json:"color,omitempty"`
	Material        string                 `protobuf:"bytes,8,opt,name=material,proto3" json:"material,omitempty"`
	ItemCondition   string                 `protobuf:"bytes,9,opt,name=item_condition,json=itemCondition,proto3" json:"item_condition,omitempty"`
	Category        string                 `protobuf:"bytes,10,opt,name=category,proto3" json:"category,omitempty"`
	LocationFound   string                 `protobuf:"bytes,11,opt,name=location_found,json=locationFound,proto3" json:"location_found,omitempty"`
	RouteOrStation  string                 `protobuf:"bytes,12,opt,name=route_or_station,json=routeOrStation,proto3" json:"route_or_station,omitempty"`
	RouteId         string                 `protobuf:"bytes,13,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	DateFound       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=date_found,json=dateFound,proto3" json:"date_found,omitempty"`
	Status          string                 `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"`
	SimilarityScore float64                `protobuf:"fixed64,16,opt,name=similarity_score,json=similarityScore,proto3" json:"similarity_score,omitempty"`
	ImageUrls       []string               `protobuf:"bytes,17,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	PrimaryImageUrl string                 `protobuf:"bytes,18,opt,name=primary_image_url,json=primaryImageUrl,proto3" json:"primary_image_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FoundItemMatch) Reset() {
	*x = FoundItemMatch{}
	mi := &file_passenger_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoundItemMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoundItemMatch) ProtoMessage() {}

func (x *FoundItemMatch) ProtoReflect() protoreflect.Message {
	mi := &file_passenger_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoundItemMatch.ProtoReflect.Descriptor instead.
func (*FoundItemMatch) Descriptor() ([]byte, []int) {
	return file_passenger_proto_rawDescGZIP(), []int{9}
}

func (x *FoundItemMatch) GetFoundItemId() string {
	if x != nil {
		return x.FoundItemId
	}
	return ""
}

func (x *FoundItemMatch) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *FoundItemMatch) GetItemDescription() string {
	if x != nil {
		return x.ItemDescription
	}
	return ""
}

func (x *FoundItemMatch) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *FoundItemMatch) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *FoundItemMatch) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *FoundItemMatch) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *FoundItemMatch) GetMaterial() string {
	if x != nil {
		return x.Material
	}
	return ""
}

func (x *FoundItemMatch) GetItemCondition() string {
	if x != nil {
		return x.ItemCondition
	}
	return ""
}

func (x *FoundItemMatch) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *FoundItemMatch) GetLocationFound() string {
	if x != nil {
		return x.LocationFound
	}
	return ""
}

func (x *FoundItemMatch) GetRouteOrStation() string {
	if x != nil {
		return x.RouteOrStation
	}
	return ""
}

func (x *FoundItemMatch) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *FoundItemMatch) GetDateFound() *timestamppb.Timestamp {
	if x != nil {
		return x.DateFound
	}
	return nil
}

func (x *FoundItemMatch) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FoundItemMatch) GetSimilarityScore() float64 {
	if x != nil {
		return x.SimilarityScore
	}
	return 0
}

func (x *FoundItemMatch) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *FoundItemMatch) GetPrimaryImageUrl() string {
	if x != nil {
		return x.PrimaryImageUrl
	}
	return ""
}

type SearchFoundItemMatchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PassengerId   string                 `protobuf:"bytes,1,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	LostReportId  string                 `protobuf:"bytes,2,opt,name=lost_report_id,json=lostReportId,proto3" json:"lost_report_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFoundItemMatchesRequest) Reset() {
	*x = SearchFoundItemMatchesRequest{}
	mi := &file_passenger_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFoundItemMatchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFoundItemMatchesRequest) ProtoMessage() {}

func (x *SearchFoundItemMatchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_passenger_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFoundItemMatchesRequest.ProtoReflect.Descriptor instead.
func (*SearchFoundItemMatchesRequest) Descriptor() ([]byte, []int) {
	return file_passenger_proto_rawDescGZIP(), []int{10}
}

func (x *SearchFoundItemMatchesRequest) GetPassengerId() string {
	if x != nil {
		return x.PassengerId
	}
	return ""
}

func (x *SearchFoundItemMatchesRequest) GetLostReportId() string {
	if x != nil {
		return x.LostReportId
	}
	return ""
}

func (x *SearchFoundItemMatchesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchFoundItemMatchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*FoundItemMatch      `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFoundItemMatchesResponse) Reset() {
	*x = SearchFoundItemMatchesResponse{}
	mi := &file_passenger_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFoundItemMatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFoundItemMatchesResponse) ProtoMessage() {}

func (x *SearchFoundItemMatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_passenger_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFoundItemMatchesResponse.ProtoReflect.Descriptor instead.
func (*SearchFoundItemMatchesResponse) Descriptor() ([]byte, []int) {
	return file_passenger_proto_rawDescGZIP(), []int{11}
}

func (x *SearchFoundItemMatchesResponse) GetMatches() []*FoundItemMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

type FileClaimRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PassengerId   string                 `protobuf:"bytes,1,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	FoundItemId   string                 `protobuf:"bytes,2,opt,name=found_item_id,json=foundItemId,proto3" json:"found_item_id,omitempty"`
	LostReportId  string                 `protobuf:"bytes,3,opt,name=lost_report_id,json=lostReportId,proto3" json:"lost_report_id,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileClaimRequest) Reset() {
	*x = FileClaimRequest{}
	mi := &file_passenger_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileClaimRequest) ProtoMessage() {}

func (x *FileClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_passenger_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileClaimRequest.ProtoReflect.Descriptor instead.
func (*FileClaimRequest) Descriptor() ([]byte, []int) {
	return file_passenger_proto_rawDescGZIP(), []int{12}
}

func (x *FileClaimRequest) GetPassengerId() string {
	if x != nil {
		return x.PassengerId
	}
	return ""
}

func (x *FileClaimRequest) GetFoundItemId() string {
	if x != nil {
		return x.FoundItemId
	}
	return ""
}

func (x *FileClaimRequest) GetLostReportId() string {
	if x != nil {
		return x.LostReportId
	}
	return ""
}

func (x *FileClaimRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ItemClaim struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemId              string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ClaimantPassengerId string                 `protobuf:"bytes,3,opt,name=claimant_passenger_id,json=claimantPassengerId,proto3" json:"claimant_passenger_id,omitempty"`
	LostReportId        string                 `protobuf:"bytes,4,opt,name=lost_report_id,json=lostReportId,proto3" json:"lost_report_id,omitempty"`
	Message             string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Status              string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ItemClaim) Reset() {
	*x = ItemClaim{}
	mi := &file_passenger_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemClaim) ProtoMessage() {}

func (x *ItemClaim) ProtoReflect() protoreflect.Message {
	mi := &file_passenger_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemClaim.ProtoReflect.Descriptor instead.
func (*ItemClaim) Descriptor() ([]byte, []int) {
	return file_passenger_proto_rawDescGZIP(), []int{13}
}

func (x *ItemClaim) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemClaim) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ItemClaim) GetClaimantPassengerId() string {
	if x != nil {
		return x.ClaimantPassengerId
	}
	return ""
}

func (x *ItemClaim) GetLostReportId() string {
	if x != nil {
		return x.LostReportId
	}
	return ""
}

func (x *ItemClaim) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ItemClaim) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ItemClaim) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ItemClaim) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListMyClaimsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyClaimsRequest) Reset() {
	*x = ListMyClaimsRequest{}
	mi := &file_passenger_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyClaimsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyClaimsRequest) ProtoMessage() {}

func (x *ListMyClaimsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_passenger_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyClaimsRequest.ProtoReflect.Descriptor instead.
func (*ListMyClaimsRequest) Descriptor() ([]byte, []int) {
	return file_passenger_proto_rawDescGZIP(), []int{14}
}

func (x *ListMyClaimsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListMyClaimsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMyClaimsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListMyClaimsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claims        []*ItemClaim           `protobuf:"bytes,1,rep,name=claims,proto3" json:"claims,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyClaimsResponse) Reset() {
	*x = ListMyClaimsResponse{}
	mi := &file_passenger_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyClaimsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyClaimsResponse) ProtoMessage() {}

func (x *ListMyClaimsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_passenger_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyClaimsResponse.ProtoReflect.Descriptor instead.
func (*ListMyClaimsResponse) Descriptor() ([]byte, []int) {
	return file_passenger_proto_rawDescGZIP(), []int{15}
}

func (x *ListMyClaimsResponse) GetClaims() []*ItemClaim {
	if x != nil {
		return x.Claims
	}
	return nil
}

type PassengerMatchNotification struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PassengerId     string                 `protobuf:"bytes,2,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	LostReportId    string                 `protobuf:"bytes,3,opt,name=lost_report_id,json=lostReportId,proto3" json:"lost_report_id,omitempty"`
	FoundItemId     string                 `protobuf:"bytes,4,opt,name=found_item_id,json=foundItemId,proto3" json:"found_item_id,omitempty"`
	SimilarityScore float64                `protobuf:"fixed64,5,opt,name=similarity_score,json=similarityScore,proto3" json:"similarity_score,omitempty"`
	ItemName        string                 `protobuf:"bytes,6,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	ImageUrls       []string               `protobuf:"bytes,7,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	PrimaryImageUrl string                 `protobuf:"bytes,8,opt,name=primary_image_url,json=primaryImageUrl,proto3" json:"primary_image_url,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ReadAt          *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=read_at,json=readAt,proto3" json:"read_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PassengerMatchNotification) Reset() {
	*x = PassengerMatchNotification{}
	mi := &file_passenger_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassengerMatchNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassengerMatchNotification) ProtoMessage() {}

func (x *PassengerMatchNotification) ProtoReflect() protoreflect.Message {
	mi := &file_passenger_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassengerMatchNotification.ProtoReflect.Descriptor instead.
func (*PassengerMatchNotification) Descriptor() ([]byte, []int) {
	return file_passenger_proto_rawDescGZIP(), []int{16}
}

func (x *PassengerMatchNotification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PassengerMatchNotification) GetPassengerId() string {
	if x != nil {
		return x.PassengerId
	}
	return ""
}

func (x *PassengerMatchNotification) GetLostReportId() string {
	if x != nil {
		return x.LostReportId
	}
	return ""
}

func (x *PassengerMatchNotification) GetFoundItemId() string {
	if x != nil {
		return x.FoundItemId
	}
	return ""
}

func (x *PassengerMatchNotification) GetSimilarityScore() float64 {
	if x != nil {
		return x.SimilarityScore
	}
	return 0
}

func (x *PassengerMatchNotification) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *PassengerMatchNotification) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *PassengerMatchNotification) GetPrimaryImageUrl() string {
	if x != nil {
		return x.PrimaryImageUrl
	}
	return ""
}

func (x *PassengerMatchNotification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PassengerMatchNotification) GetReadAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReadAt
	}
	return nil
}

type ListNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	UnreadOnly    bool                   `protobuf:"varint,2,opt,name=unread_only,json=unreadOnly,proto3" json:"unread_only,omitempty"`
	CreatedBefore *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_before,json=createdBefore,proto3" json:"created_before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_passenger_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_passenger_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_passenger_proto_rawDescGZIP(), []int{17}
}

func (x *ListNotificationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListNotificationsRequest) GetUnreadOnly() bool {
	if x != nil {
		return x.UnreadOnly
	}
	return false
}

func (x *ListNotificationsRequest) GetCreatedBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedBefore
	}
	return nil
}

type ListNotificationsResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Notifications []*PassengerMatchNotification `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_passenger_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_passenger_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_passenger_proto_rawDescGZIP(), []int{18}
}

func (x *ListNotificationsResponse) GetNotifications() []*PassengerMatchNotification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type MarkNotificationReadRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NotificationIds []string               `protobuf:"bytes,1,rep,name=notification_ids,json=notificationIds,proto3" json:"notification_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MarkNotificationReadRequest) Reset() {
	*x = MarkNotificationReadRequest{}
	mi := &file_passenger_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkNotificationReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkNotificationReadRequest) ProtoMessage() {}

func (x *MarkNotificationReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_passenger_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkNotificationReadRequest.ProtoReflect.Descriptor instead.
func (*MarkNotificationReadRequest) Descriptor() ([]byte, []int) {
	return file_passenger_proto_rawDescGZIP(), []int{19}
}

func (x *MarkNotificationReadRequest) GetNotificationIds() []string {
	if x != nil {
		return x.NotificationIds
	}
	return nil
}

var File_passenger_proto protoreflect.FileDescriptor

const file_passenger_proto_rawDesc = "" +
	"\n" +
	"\x0fpassenger.proto\x12\x16smartfind.passenger.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x01\n" +
	"\tPassenger\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\a \x01(\tR\tavatarUrl\")\n" +
	"\fLoginRequest\x12\x19\n" +
	"\bid_token\x18\x01 \x01(\tR\aidToken\"u\n" +
	"\rLoginResponse\x12?\n" +
	"\tpassenger\x18\x01 \x01(\v2!.smartfind.passenger.v1.PassengerR\tpassenger\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\"\x87\x05\n" +
	"\n" +
	"LostReport\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x15reporter_passenger_id\x18\x02 \x01(\tR\x13reporterPassengerId\x12\x1b\n" +
	"\titem_name\x18\x03 \x01(\tR\bitemName\x12)\n" +
	"\x10item_description\x18\x04 \x01(\tR\x0fitemDescription\x12\x1b\n" +
	"\titem_type\x18\x05 \x01(\tR\bitemType\x12\x14\n" +
	"\x05brand\x18\x06 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\a \x01(\tR\x05model\x12\x14\n" +
	"\x05color\x18\b \x01(\tR\x05color\x12\x1a\n" +
	"\bmaterial\x18\t \x01(\tR\bmaterial\x12%\n" +
	"\x0eitem_condition\x18\n" +
	" \x01(\tR\ritemCondition\x12\x1a\n" +
	"\bcategory\x18\v \x01(\tR\bcategory\x12#\n" +
	"\rlocation_lost\x18\f \x01(\tR\flocationLost\x12(\n" +
	"\x10route_or_station\x18\r \x01(\tR\x0erouteOrStation\x12\x19\n" +
	"\broute_id\x18\x0e \x01(\tR\arouteId\x127\n" +
	"\tdate_lost\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\bdateLost\x12\x16\n" +
	"\x06status\x18\x10 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe5\x03\n" +
	"\x17CreateLostReportRequest\x12!\n" +
	"\fpassenger_id\x18\x01 \x01(\tR\vpassengerId\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12)\n" +
	"\x10item_description\x18\x03 \x01(\tR\x0fitemDescription\x12\x1b\n" +
	"\titem_type\x18\x04 \x01(\tR\bitemType\x12\x14\n" +
	"\x05brand\x18\x05 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x06 \x01(\tR\x05model\x12\x14\n" +
	"\x05color\x18\a \x01(\tR\x05color\x12\x1a\n" +
	"\bmaterial\x18\b \x01(\tR\bmaterial\x12%\n" +
	"\x0eitem_condition\x18\t \x01(\tR\ritemCondition\x12\x1a\n" +
	"\bcategory\x18\n" +
	" \x01(\tR\bcategory\x12#\n" +
	"\rlocation_lost\x18\v \x01(\tR\flocationLost\x12(\n" +
	"\x10route_or_station\x18\f \x01(\tR\x0erouteOrStation\x12\x19\n" +
	"\broute_id\x18\r \x01(\tR\arouteId\x127\n" +
	"\tdate_lost\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\bdateLost\"\x8b\x04\n" +
	"\x17UpdateLostReportRequest\x12!\n" +
	"\fpassenger_id\x18\x01 \x01(\tR\vpassengerId\x12$\n" +
	"\x0elost_report_id\x18\x02 \x01(\tR\flostReportId\x12\x1b\n" +
	"\titem_name\x18\x03 \x01(\tR\bitemName\x12)\n" +
	"\x10item_description\x18\x04 \x01(\tR\x0fitemDescription\x12\x1b\n" +
	"\titem_type\x18\x05 \x01(\tR\bitemType\x12\x14\n" +
	"\x05brand\x18\x06 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\a \x01(\tR\x05model\x12\x14\n" +
	"\x05color\x18\b \x01(\tR\x05color\x12\x1a\n" +
	"\bmaterial\x18\t \x01(\tR\bmaterial\x12%\n" +
	"\x0eitem_condition\x18\n" +
	" \x01(\tR\ritemCondition\x12\x1a\n" +
	"\bcategory\x18\v \x01(\tR\bcategory\x12#\n" +
	"\rlocation_lost\x18\f \x01(\tR\flocationLost\x12(\n" +
	"\x10route_or_station\x18\r \x01(\tR\x0erouteOrStation\x12\x19\n" +
	"\broute_id\x18\x0e \x01(\tR\arouteId\x127\n" +
	"\tdate_lost\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\bdateLost\"S\n" +
	"\x16ListLostReportsRequest\x12!\n" +
	"\fpassenger_id\x18\x01 \x01(\tR\vpassengerId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"W\n" +
	"\x17ListLostReportsResponse\x12<\n" +
	"\areports\x18\x01 \x03(\v2\".smartfind.passenger.v1.LostReportR\areports\"b\n" +
	"\x17DeleteLostReportRequest\x12!\n" +
	"\fpassenger_id\x18\x01 \x01(\tR\vpassengerId\x12$\n" +
	"\x0elost_report_id\x18\x02 \x01(\tR\flostReportId\"\xef\x04\n" +
	"\x0eFoundItemMatch\x12\"\n" +
	"\rfound_item_id\x18\x01 \x01(\tR\vfoundItemId\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12)\n" +
	"\x10item_description\x18\x03 \x01(\tR\x0fitemDescription\x12\x1b\n" +
	"\titem_type\x18\x04 \x01(\tR\bitemType\x12\x14\n" +
	"\x05brand\x18\x05 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x06 \x01(\tR\x05model\x12\x14\n" +
	"\x05color\x18\a \x01(\tR\x05color\x12\x1a\n" +
	"\bmaterial\x18\b \x01(\tR\bmaterial\x12%\n" +
	"\x0eitem_condition\x18\t \x01(\tR\ritemCondition\x12\x1a\n" +
	"\bcategory\x18\n" +
	" \x01(\tR\bcategory\x12%\n" +
	"\x0elocation_found\x18\v \x01(\tR\rlocationFound\x12(\n" +
	"\x10route_or_station\x18\f \x01(\tR\x0erouteOrStation\x12\x19\n" +
	"\broute_id\x18\r \x01(\tR\arouteId\x129\n" +
	"\n" +
	"date_found\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tdateFound\x12\x16\n" +
	"\x06status\x18\x0f \x01(\tR\x06status\x12)\n" +
	"\x10similarity_score\x18\x10 \x01(\x01R\x0fsimilarityScore\x12\x1d\n" +
	"\n" +
	"image_urls\x18\x11 \x03(\tR\timageUrls\x12*\n" +
	"\x11primary_image_url\x18\x12 \x01(\tR\x0fprimaryImageUrl\"~\n" +
	"\x1dSearchFoundItemMatchesRequest\x12!\n" +
	"\fpassenger_id\x18\x01 \x01(\tR\vpassengerId\x12$\n" +
	"\x0elost_report_id\x18\x02 \x01(\tR\flostReportId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"b\n" +
	"\x1eSearchFoundItemMatchesResponse\x12@\n" +
	"\amatches\x18\x01 \x03(\v2&.smartfind.passenger.v1.FoundItemMatchR\amatches\"\x99\x01\n" +
	"\x10FileClaimRequest\x12!\n" +
	"\fpassenger_id\x18\x01 \x01(\tR\vpassengerId\x12\"\n" +
	"\rfound_item_id\x18\x02 \x01(\tR\vfoundItemId\x12$\n" +
	"\x0elost_report_id\x18\x03 \x01(\tR\flostReportId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xb6\x02\n" +
	"\tItemClaim\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x122\n" +
	"\x15claimant_passenger_id\x18\x03 \x01(\tR\x13claimantPassengerId\x12$\n" +
	"\x0elost_report_id\x18\x04 \x01(\tR\flostReportId\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"[\n" +
	"\x13ListMyClaimsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"Q\n" +
	"\x14ListMyClaimsResponse\x129\n" +
	"\x06claims\x18\x01 \x03(\v2!.smartfind.passenger.v1.ItemClaimR\x06claims\"\x9c\x03\n" +
	"\x1aPassengerMatchNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fpassenger_id\x18\x02 \x01(\tR\vpassengerId\x12$\n" +
	"\x0elost_report_id\x18\x03 \x01(\tR\flostReportId\x12\"\n" +
	"\rfound_item_id\x18\x04 \x01(\tR\vfoundItemId\x12)\n" +
	"\x10similarity_score\x18\x05 \x01(\x01R\x0fsimilarityScore\x12\x1b\n" +
	"\titem_name\x18\x06 \x01(\tR\bitemName\x12\x1d\n" +
	"\n" +
	"image_urls\x18\a \x03(\tR\timageUrls\x12*\n" +
	"\x11primary_image_url\x18\b \x01(\tR\x0fprimaryImageUrl\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x123\n" +
	"\aread_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x06readAt\"\x94\x01\n" +
	"\x18ListNotificationsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vunread_only\x18\x02 \x01(\bR\n" +
	"unreadOnly\x12A\n" +
	"\x0ecreated_before\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rcreatedBefore\"u\n" +
	"\x19ListNotificationsResponse\x12X\n" +
	"\rnotifications\x18\x01 \x03(\v22.smartfind.passenger.v1.PassengerMatchNotificationR\rnotifications\"H\n" +
	"\x1bMarkNotificationReadRequest\x12)\n" +
	"\x10notification_ids\x18\x01 \x03(\tR\x0fnotificationIds2\xb9\b\n" +
	"\x10PassengerService\x12T\n" +
	"\x05Login\x12$.smartfind.passenger.v1.LoginRequest\x1a%.smartfind.passenger.v1.LoginResponse\x12g\n" +
	"\x10CreateLostReport\x12/.smartfind.passenger.v1.CreateLostReportRequest\x1a\".smartfind.passenger.v1.LostReport\x12g\n" +
	"\x10UpdateLostReport\x12/.smartfind.passenger.v1.UpdateLostReportRequest\x1a\".smartfind.passenger.v1.LostReport\x12r\n" +
	"\x0fListLostReports\x12..smartfind.passenger.v1.ListLostReportsRequest\x1a/.smartfind.passenger.v1.ListLostReportsResponse\x12[\n" +
	"\x10DeleteLostReport\x12/.smartfind.passenger.v1.DeleteLostReportRequest\x1a\x16.google.protobuf.Empty\x12\x87\x01\n" +
	"\x16SearchFoundItemMatches\x125.smartfind.passenger.v1.SearchFoundItemMatchesRequest\x1a6.smartfind.passenger.v1.SearchFoundItemMatchesResponse\x12X\n" +
	"\tFileClaim\x12(.smartfind.passenger.v1.FileClaimRequest\x1a!.smartfind.passenger.v1.ItemClaim\x12i\n" +
	"\fListMyClaims\x12+.smartfind.passenger.v1.ListMyClaimsRequest\x1a,.smartfind.passenger.v1.ListMyClaimsResponse\x12x\n" +
	"\x11ListNotifications\x120.smartfind.passenger.v1.ListNotificationsRequest\x1a1.smartfind.passenger.v1.ListNotificationsResponse\x12c\n" +
	"\x14MarkNotificationRead\x123.smartfind.passenger.v1.MarkNotificationReadRequest\x1a\x16.google.protobuf.EmptyB\x1dZ\x1bsmartfind/proto;smartfindpbb\x06proto3"

var (
	file_passenger_proto_rawDescOnce sync.Once
	file_passenger_proto_rawDescData []byte
)

func file_passenger_proto_rawDescGZIP() []byte {
	file_passenger_proto_rawDescOnce.Do(func() {
		file_passenger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_passenger_proto_rawDesc), len(file_passenger_proto_rawDesc)))
	})
	return file_passenger_proto_rawDescData
}

var file_passenger_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_passenger_proto_goTypes = []any{
	(*Passenger)(nil),                      // 0: smartfind.passenger.v1.Passenger
	(*LoginRequest)(nil),                   // 1: smartfind.passenger.v1.LoginRequest
	(*LoginResponse)(nil),                  // 2: smartfind.passenger.v1.LoginResponse
	(*LostReport)(nil),                     // 3: smartfind.passenger.v1.LostReport
	(*CreateLostReportRequest)(nil),        // 4: smartfind.passenger.v1.CreateLostReportRequest
	(*UpdateLostReportRequest)(nil),        // 5: smartfind.passenger.v1.UpdateLostReportRequest
	(*ListLostReportsRequest)(nil),         // 6: smartfind.passenger.v1.ListLostReportsRequest
	(*ListLostReportsResponse)(nil),        // 7: smartfind.passenger.v1.ListLostReportsResponse
	(*DeleteLostReportRequest)(nil),        // 8: smartfind.passenger.v1.DeleteLostReportRequest
	(*FoundItemMatch)(nil),                 // 9: smartfind.passenger.v1.FoundItemMatch
	(*SearchFoundItemMatchesRequest)(nil),  // 10: smartfind.passenger.v1.SearchFoundItemMatchesRequest
	(*SearchFoundItemMatchesResponse)(nil), // 11: smartfind.passenger.v1.SearchFoundItemMatchesResponse
	(*FileClaimRequest)(nil),               // 12: smartfind.passenger.v1.FileClaimRequest
	(*ItemClaim)(nil),                      // 13: smartfind.passenger.v1.ItemClaim
	(*ListMyClaimsRequest)(nil),            // 14: smartfind.passenger.v1.ListMyClaimsRequest
	(*ListMyClaimsResponse)(nil),           // 15: smartfind.passenger.v1.ListMyClaimsResponse
	(*PassengerMatchNotification)(nil),     // 16: smartfind.passenger.v1.PassengerMatchNotification
	(*ListNotificationsRequest)(nil),       // 17: smartfind.passenger.v1.ListNotificationsRequest
	(*ListNotificationsResponse)(nil),      // 18: smartfind.passenger.v1.ListNotificationsResponse
	(*MarkNotificationReadRequest)(nil),    // 19: smartfind.passenger.v1.MarkNotificationReadRequest
	(*timestamppb.Timestamp)(nil),          // 20: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                  // 21: google.protobuf.Empty
}
var file_passenger_proto_depIdxs = []int32{
	20, // 0: smartfind.passenger.v1.Passenger.created_at:type_name -> google.protobuf.Timestamp
	20, // 1: smartfind.passenger.v1.Passenger.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: smartfind.passenger.v1.LoginResponse.passenger:type_name -> smartfind.passenger.v1.Passenger
	20, // 3: smartfind.passenger.v1.LostReport.date_lost:type_name -> google.protobuf.Timestamp
	20, // 4: smartfind.passenger.v1.LostReport.created_at:type_name -> google.protobuf.Timestamp
	20, // 5: smartfind.passenger.v1.LostReport.updated_at:type_name -> google.protobuf.Timestamp
	20, // 6: smartfind.passenger.v1.CreateLostReportRequest.date_lost:type_name -> google.protobuf.Timestamp
	20, // 7: smartfind.passenger.v1.UpdateLostReportRequest.date_lost:type_name -> google.protobuf.Timestamp
	3,  // 8: smartfind.passenger.v1.ListLostReportsResponse.reports:type_name -> smartfind.passenger.v1.LostReport
	20, // 9: smartfind.passenger.v1.FoundItemMatch.date_found:type_name -> google.protobuf.Timestamp
	9,  // 10: smartfind.passenger.v1.SearchFoundItemMatchesResponse.matches:type_name -> smartfind.passenger.v1.FoundItemMatch
	20, // 11: smartfind.passenger.v1.ItemClaim.created_at:type_name -> google.protobuf.Timestamp
	20, // 12: smartfind.passenger.v1.ItemClaim.updated_at:type_name -> google.protobuf.Timestamp
	13, // 13: smartfind.passenger.v1.ListMyClaimsResponse.claims:type_name -> smartfind.passenger.v1.ItemClaim
	20, // 14: smartfind.passenger.v1.PassengerMatchNotification.created_at:type_name -> google.protobuf.Timestamp
	20, // 15: smartfind.passenger.v1.PassengerMatchNotification.read_at:type_name -> google.protobuf.Timestamp
	20, // 16: smartfind.passenger.v1.ListNotificationsRequest.created_before:type_name -> google.protobuf.Timestamp
	16, // 17: smartfind.passenger.v1.ListNotificationsResponse.notifications:type_name -> smartfind.passenger.v1.PassengerMatchNotification
	1,  // 18: smartfind.passenger.v1.PassengerService.Login:input_type -> smartfind.passenger.v1.LoginRequest
	4,  // 19: smartfind.passenger.v1.PassengerService.CreateLostReport:input_type -> smartfind.passenger.v1.CreateLostReportRequest
	5,  // 20: smartfind.passenger.v1.PassengerService.UpdateLostReport:input_type -> smartfind.passenger.v1.UpdateLostReportRequest
	6,  // 21: smartfind.passenger.v1.PassengerService.ListLostReports:input_type -> smartfind.passenger.v1.ListLostReportsRequest
	8,  // 22: smartfind.passenger.v1.PassengerService.DeleteLostReport:input_type -> smartfind.passenger.v1.DeleteLostReportRequest
	10, // 23: smartfind.passenger.v1.PassengerService.SearchFoundItemMatches:input_type -> smartfind.passenger.v1.SearchFoundItemMatchesRequest
	12, // 24: smartfind.passenger.v1.PassengerService.FileClaim:input_type -> smartfind.passenger.v1.FileClaimRequest
	14, // 25: smartfind.passenger.v1.PassengerService.ListMyClaims:input_type -> smartfind.passenger.v1.ListMyClaimsRequest
	17, // 26: smartfind.passenger.v1.PassengerService.ListNotifications:input_type -> smartfind.passenger.v1.ListNotificationsRequest
	19, // 27: smartfind.passenger.v1.PassengerService.MarkNotificationRead:input_type -> smartfind.passenger.v1.MarkNotificationReadRequest
	2,  // 28: smartfind.passenger.v1.PassengerService.Login:output_type -> smartfind.passenger.v1.LoginResponse
	3,  // 29: smartfind.passenger.v1.PassengerService.CreateLostReport:output_type -> smartfind.passenger.v1.LostReport
	3,  // 30: smartfind.passenger.v1.PassengerService.UpdateLostReport:output_type -> smartfind.passenger.v1.LostReport
	7,  // 31: smartfind.passenger.v1.PassengerService.ListLostReports:output_type -> smartfind.passenger.v1.ListLostReportsResponse
	21, // 32: smartfind.passenger.v1.PassengerService.DeleteLostReport:output_type -> google.protobuf.Empty
	11, // 33: smartfind.passenger.v1.PassengerService.SearchFoundItemMatches:output_type -> smartfind.passenger.v1.SearchFoundItemMatchesResponse
	13, // 34: smartfind.passenger.v1.PassengerService.FileClaim:output_type -> smartfind.passenger.v1.ItemClaim
	15, // 35: smartfind.passenger.v1.PassengerService.ListMyClaims:output_type -> smartfind.passenger.v1.ListMyClaimsResponse
	18, // 36: smartfind.passenger.v1.PassengerService.ListNotifications:output_type -> smartfind.passenger.v1.ListNotificationsResponse
	21, // 37: smartfind.passenger.v1.PassengerService.MarkNotificationRead:output_type -> google.protobuf.Empty
	28, // [28:38] is the sub-list for method output_type
	18, // [18:28] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_passenger_proto_init() }
func file_passenger_proto_init() {
	if File_passenger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_passenger_proto_rawDesc), len(file_passenger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_passenger_proto_goTypes,
		DependencyIndexes: file_passenger_proto_depIdxs,
		MessageInfos:      file_passenger_proto_msgTypes,
	}.Build()
	File_passenger_proto = out.File
	file_passenger_proto_goTypes = nil
	file_passenger_proto_depIdxs = nil
}
