# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: detailextractor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'detailextractor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64\x65tailextractor.proto\x12\x1csmartfind.detailextractor.v1\"&\n\x0e\x45xtractRequest\x12\x14\n\x0cimage_base64\x18\x01 \x01(\t\"\xba\x01\n\x0f\x45xtractResponse\x12\x11\n\titem_name\x18\x01 \x01(\t\x12\x11\n\titem_type\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\r\n\x05\x62rand\x18\x04 \x01(\t\x12\r\n\x05model\x18\x05 \x01(\t\x12\r\n\x05\x63olor\x18\x06 \x01(\t\x12\x10\n\x08material\x18\x07 \x01(\t\x12\x16\n\x0eitem_condition\x18\x08 \x01(\t\x12\x18\n\x10item_description\x18\t \x01(\t2\x80\x01\n\x16\x44\x65tailExtractorService\x12\x66\n\x07\x45xtract\x12,.smartfind.detailextractor.v1.ExtractRequest\x1a-.smartfind.detailextractor.v1.ExtractResponseB\x1dZ\x1bsmartfind/proto;smartfindpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detailextractor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\033smartfind/proto;smartfindpb'
  _globals['_EXTRACTREQUEST']._serialized_start=55
  _globals['_EXTRACTREQUEST']._serialized_end=93
  _globals['_EXTRACTRESPONSE']._serialized_start=96
  _globals['_EXTRACTRESPONSE']._serialized_end=282
  _globals['_DETAILEXTRACTORSERVICE']._serialized_start=285
  _globals['_DETAILEXTRACTORSERVICE']._serialized_end=413
# @@protoc_insertion_point(module_scope)
